/// <reference types="node" />
import assert from 'node:assert/strict'
import fs from 'node:fs'
const branding = fs.readFileSync('src/branding/branding.ts', 'utf8')
assert.match(branding, /export type BrandingFamily = 'spartan' \| 'amazonian'/)
assert.match(branding, /spartan:[\s\S]*logo: '\/branding\/fitdex-logo-spartan\.png'[\s\S]*icon: '\/branding\/fitdex-icon-spartan\.png'/)
assert.match(branding, /amazonian:[\s\S]*logo: '\/branding\/fitdex-logo-amazonian\.png'[\s\S]*icon: '\/branding\/fitdex-icon-amazonian\.png'/)
assert.match(branding, /family === 'amazonians' \? 'amazonian' : 'spartan'/)
assert.match(branding, /querySelector<HTMLLinkElement>\('link\[rel="icon"\]'\)/)
assert.match(branding, /if \(!link\)[\s\S]*documentRef\.head\.append\(link\)/)
assert.match(branding, /link\.href = icon/)
for (const file of ['fitdex-logo-spartan.png', 'fitdex-logo-amazonian.png', 'fitdex-icon-spartan.png', 'fitdex-icon-amazonian.png']) assert.ok(fs.existsSync(`public/branding/${file}`), `${file} must exist`)
const shell = fs.readFileSync('src/components/layout/AppShell.tsx', 'utf8')
assert.match(shell, /brandingForTheme\(family\)/)
assert.match(shell, /media="\(min-width: 600px\)"/)
assert.match(shell, /wordmark-mobile-name/)
assert.match(shell, /<button className="wordmark"/)
assert.match(shell, /useResolvedBrightness/)
assert.match(shell, /setBrightness\(resolvedBrightness === 'dark' \? 'light' : 'dark'\)/)
assert.match(shell, /className="header-utility-key theme-utility-key"/)
assert.match(shell, /RetroSunIcon|RetroMoonIcon/)
assert.match(shell, /className=\{`header-utility-key settings-utility-key \$\{settingsOpen \? 'is-active' : ''\}`\}/)
assert.match(shell, /RetroGearIcon/)
const headerIcons = fs.readFileSync('src/components/layout/HeaderUtilityIcons.tsx', 'utf8')
assert.match(headerIcons, /export function RetroSunIcon/)
assert.match(headerIcons, /export function RetroMoonIcon/)
assert.match(headerIcons, /export function RetroGearIcon/)
const styles = fs.readFileSync('src/styles/app.css', 'utf8')
assert.match(styles, /\.wordmark-image \{[^}]*object-fit: contain/s)
assert.match(styles, /@media \(min-width: 600px\)\s*\{[\s\S]*?\.wordmark-image\s*\{[^}]*width:\s*auto;[^}]*max-width:\s*190px;[^}]*height:\s*52px;/)
assert.match(styles, /\.header-actions\s*\{[^}]*gap:\s*8px;[^}]*margin-left:\s*auto;/s)
assert.doesNotMatch(styles, /\.header-actions\s*\{[^}]*border:|\.header-actions\s*\{[^}]*background:|\.header-actions\s*\{[^}]*box-shadow:/s)
assert.match(styles, /\.header-utility-key\s*\{[^}]*width:\s*44px;[^}]*border-radius:\s*10px;[^}]*box-shadow:/s)
assert.match(styles, /\.header-utility-key:active\s*\{[^}]*transform:\s*translateY\(1px\) scale\(\.98\);/s)
assert.match(styles, /\.theme-utility-key \.retro-sun-rays\s*\{[^}]*--color-utility-sun-shadow/s)
assert.match(styles, /\.theme-utility-key \.retro-moon-body\s*\{[^}]*--color-utility-moon-base/s)
assert.match(styles, /\.settings-utility-key \.retro-gear-rotor\s*\{[^}]*animation:\s*retro-gear-turn 10s linear infinite;/s)
assert.match(styles, /@keyframes retro-gear-turn\s*\{\s*to\s*\{\s*transform:\s*rotate\(360deg\);/s)
assert.match(styles, /@media \(prefers-reduced-motion: reduce\)\s*\{\s*\.settings-utility-key \.retro-gear-rotor\s*\{\s*animation:\s*none;/s)
const themeTokens = fs.readFileSync('src/index.css', 'utf8')
assert.match(themeTokens, /--color-utility-gear-base:/)
assert.match(themeTokens, /--color-utility-gear-highlight:/)
assert.match(themeTokens, /--color-utility-gear-shadow:/)
const native = fs.readFileSync('src/branding/nativeBranding.ts', 'utf8')
assert.match(native, /Capacitor\.isNativePlatform\(\)/)
assert.match(native, /export function supportsNativeAndroidLauncherBranding\(\)/)
assert.match(native, /Capacitor\.getPlatform\(\) === 'android'/)
assert.match(native, /Capacitor\.isPluginAvailable\('LauncherBranding'\)/)
assert.match(native, /!supportsNativeAndroidLauncherBranding\(\) \|\| activeFamily === family/)
assert.match(native, /activeFamily === family/)
assert.match(native, /setLauncherBranding\(\{ family \}\)/)
assert.match(native, /setLauncherBranding\(\{ family, relaunch: true \}\)/)

console.log('Branding assertions passed: family mapping, exact assets, responsive header, favicon replacement, and native LauncherBranding availability/idempotency guards')
