/// <reference types="node" />
import assert from 'node:assert/strict'
import fs from 'node:fs'
import { AVATARS } from '../avatar/avatars.ts'

const page = fs.readFileSync('src/pages/HomePage.tsx', 'utf8')
const css = fs.readFileSync('src/styles/app.css', 'utf8')
const avatar = fs.readFileSync('src/features/avatar/AvatarPortrait.tsx', 'utf8')
const settings = fs.readFileSync('src/features/settings/SettingsPage.tsx', 'utf8')
const app = fs.readFileSync('src/app/App.tsx', 'utf8')
const vite = fs.readFileSync('vite.config.ts', 'utf8')
const database = fs.readFileSync('src/data/database.ts', 'utf8')
const models = fs.readFileSync('src/data/models.ts', 'utf8')

assert.match(page, /<AvatarPortrait avatar=\{selectedAvatar\} size="medium" priority/)
assert.match(page, /Resume Workout/)
assert.match(page, /Workout paused/)
assert.match(page, /Open Paused Workout/)
assert.match(page, /getWorkoutDuration/)
assert.match(page, /Start Workout/)
assert.match(page, /Workout Day Complete/)
assert.match(page, /completedByStartDate/)
assert.match(page, /No workout planned yet/)
assert.match(page, /No routine assigned/)
assert.match(page, /Rest Day/)
assert.match(page, /Start \{data\.scheduledRoutine\.routine\.name\}/)
assert.match(page, /Set Weekly Plan/)
assert.match(page, /Create Routine/)
assert.match(page, /Workouts and food you log automatically feed into Home, Journal and Progress/)
assert.match(page, /Nutrition today/)
assert.match(page, /FOOD_MEAL_LABELS/)
assert.match(page, /Today's activity/)
assert.match(page, /formatPersonalRecordMetric/)
assert.match(page, /last7WorkoutCount/)
assert.match(page, /Quick access/)
assert.match(page, /Exercise Dex/)
assert.match(page, /Journal/)
assert.match(page, /View Progress/)
assert.doesNotMatch(page, /demoProgress|Experience|\bXP\b|streak|Daily quest|calorie goal/i)
assert.match(app, /<ProfileProvider>/)
assert.match(app, /<HomePage onNavigate=\{setDestination\} onOpenWorkout=/)
assert.match(app, /<WorkoutPage initialView=\{workoutEntry\} initialRoutineId=/)

assert.match(settings, />Display Name</)
assert.match(settings, /This is what FitDex calls you/)
assert.match(settings, /Use up to \{MAX_DISPLAY_NAME_LENGTH\} characters/)
assert.doesNotMatch(settings, /maxLength=/, 'HTML maxLength counts UTF-16 code units and would prematurely limit astral Unicode characters')
assert.match(settings, /Save Display Name/)
assert.match(models, /displayName\?: string/)
assert.match(database, /DATABASE_SCHEMA_VERSION = 6/)
assert.doesNotMatch(database, /homeDashboard|homeSummary|dailyHomeState/)

assert.match(avatar, /loading=\{priority \? 'eager' : 'lazy'\}/)
assert.match(avatar, /fetchPriority=\{priority \? 'high' : 'auto'\}/)
assert.match(avatar, /width=\{384\}/)
assert.match(avatar, /height=\{576\}/)
assert.match(avatar, /imageStatus !== 'loaded'/)
assert.equal(AVATARS.length, 6)
for (const item of AVATARS) {
  const bytes = fs.readFileSync(`public${item.assetPath}`)
  assert.equal(bytes.toString('ascii', 1, 4), 'PNG')
  assert.equal(bytes.readUInt32BE(16), 384)
  assert.equal(bytes.readUInt32BE(20), 576)
  assert.ok(bytes.byteLength < 400_000, `${item.id} avatar should remain below 400 KB`)
}
assert.match(vite, /globPatterns: \['\*\*\/\*\.\{js,css,html,svg,png,woff2\}'\]/)
assert.doesNotMatch(vite, /mp4/)

assert.match(css, /\.home-hero \{[^}]*grid-template-columns: auto minmax\(0, 1fr\)/s)
assert.match(css, /\.home-quick-access \{[^}]*grid-template-columns: repeat\(2,/s)
assert.match(css, /\.home-week-grid \{[^}]*grid-template-columns: repeat\(7,/s)
assert.match(css, /@media \(max-width: 374px\)[\s\S]*\.home-meal-status \{ grid-template-columns: 1fr; \}/)
assert.match(css, /\.display-name-form input \{[^}]*min-height: 48px;/s)
assert.doesNotMatch(css.match(/\/\* Home Dashboard V1[\s\S]*$/)?.[0] ?? '', /#[0-9a-f]{3,8}/i)

console.log('Home UI assertions passed: real dashboard sections, navigation intents, local profile form, priority avatars, optimized assets, PWA safety, responsive classes, accessibility, and theme tokens')
