/// <reference types="node" />
import assert from 'node:assert/strict'
import fs from 'node:fs'
import { AVATARS } from '../avatar/avatars.ts'

const page = fs.readFileSync('src/pages/HomePage.tsx', 'utf8')
const css = fs.readFileSync('src/styles/app.css', 'utf8')
const battleMusic = fs.readFileSync('src/components/ui/BattleMusicDeck.tsx', 'utf8')
const themeCss = fs.readFileSync('src/index.css', 'utf8')
const avatar = fs.readFileSync('src/features/avatar/AvatarPortrait.tsx', 'utf8')
const settings = fs.readFileSync('src/features/settings/SettingsPage.tsx', 'utf8')
const app = fs.readFileSync('src/app/App.tsx', 'utf8')
const vite = fs.readFileSync('vite.config.ts', 'utf8')
const database = fs.readFileSync('src/data/database.ts', 'utf8')
const models = fs.readFileSync('src/data/models.ts', 'utf8')
const appShell = fs.readFileSync('src/components/layout/AppShell.tsx', 'utf8')
const packageJson = JSON.parse(fs.readFileSync('package.json', 'utf8')) as { version: string }

assert.match(page, /<AvatarPortrait avatar=\{selectedAvatar\} size="medium" priority/)
assert.match(page, /Resume Workout/)
assert.match(page, /Workout paused/)
assert.match(page, /Open Paused Workout/)
assert.match(page, /getWorkoutDuration/)
assert.match(page, /Start Workout/)
assert.match(page, /Workout Day Complete/)
assert.match(page, /completedByStartDate/)
assert.match(page, /No workout planned yet/)
assert.match(page, /No routine assigned/)
assert.match(page, /Rest Day/)
assert.match(page, /Start \{data\.scheduledRoutine\.routine\.name\}/)
assert.match(page, /Set Weekly Plan/)
assert.match(page, /Create Routine/)
assert.match(page, /Workouts and food you log automatically feed into Home, Journal and Progress/)
assert.match(page, /Nutrition today/)
assert.match(page, /FOOD_MEAL_LABELS/)
assert.match(page, /Today's activity/)
assert.match(page, /formatPersonalRecordMetric/)
assert.match(page, /last7WorkoutCount/)
assert.match(page, /Quick access/)
assert.match(page, /Battle Music/)
assert.match(page, /Previous background track/)
assert.match(page, /Pause background music/)
assert.match(page, /Resume background music/)
assert.match(page, /Next background track/)
assert.match(page, /Turn background music off/)
assert.match(page, /BACKGROUND_TRACK_ORDER\.map/)
assert.match(page, /cycleBackgroundTrack/)
assert.match(page, /Exercise Dex/)
assert.match(page, /Journal/)
assert.match(page, /View Progress/)
assert.doesNotMatch(page, /demoProgress|calorie goal/i)
assert.match(page, /LevelProgress/)
assert.match(page, /Plan Streak/)
assert.match(page, /Today's Quest/)
assert.match(page, /home-hero-player/)
assert.match(page, /home-command-status/)
assert.match(page, /home-command-rank/)
assert.match(page, /rankAssetPath\(progression\.rank\)/)
assert.match(page, /GamificationBadge kind="rank" size="small"/)
assert.match(page, /progression\.rank\.name/)
assert.doesNotMatch(page, />VII<|6,840 XP|VANGUARD/)
assert.match(page, /home-desktop-hero/)
assert.match(page, /DesktopTodayWorkoutPanel/)
assert.match(page, /MobileHomeSupport/)
for (const command of ["Today's Mission", 'Nutrition', 'Progress', 'Achievements', 'Journal', 'Battle Music']) assert.match(page, new RegExp(command))
assert.doesNotMatch(page, /More from today/)
assert.match(page, /MobileMusicRow/)
assert.match(page, /home-mobile-music-tracks/)
assert.match(page, /<BattleMusicDeck className="home-mobile-music-tracks"/)
assert.match(battleMusic, /BATTLE MUSIC/)
assert.match(battleMusic, /BGM DECK/)
assert.doesNotMatch(battleMusic, /SELECT CHANNEL/)
assert.match(page, /import \{ AudioEqualizer, BattleMusicDeck \}/)
assert.match(page, /HomeMusicStatus/)
assert.match(page, /function CommandRow[\s\S]*?className="home-command-number"/)
assert.match(page, /<span className="home-command-number">\{number\}<\/span><b>Battle Music<\/b>/)
assert.match(css, /\.home-command-row>\.home-command-number,\s*\.home-command-music-row \.home-command-number\s*\{[^}]*width:\s*28px;[^}]*height:\s*28px;[^}]*border-radius:\s*7px;/s)
assert.match(css, /@keyframes music-equalizer-level/)
assert.match(css, /@media \(prefers-reduced-motion: reduce\)\s*\{\s*\.music-equalizer i\s*\{\s*animation: none;/s)
for (const track of ['Warrior', 'Hardened', 'Villain', 'None']) assert.match(battleMusic, new RegExp(track))
assert.match(battleMusic, /function PixelMuteIcon/)
assert.match(battleMusic, /<PixelMuteIcon \/><b>ACTIVE<\/b>/)
assert.doesNotMatch(battleMusic, /<b>OFF<\/b>/)
assert.match(battleMusic, /shapeRendering="crispEdges"/)
assert.match(css, /\.music-mute-icon \{[^}]*width: 16px;[^}]*height: 13px;/s)
assert.match(page, /playEffect\('select'\)[\s\S]*setBackgroundMusic\(track\)/)
const mobileMusic = page.slice(page.indexOf('function MobileMusicRow'), page.indexOf('function TodayWorkoutPanel'))
assert.doesNotMatch(mobileMusic, /setExpanded\(false\)/)
const mobileSupport = page.slice(page.indexOf('function MobileHomeSupport'), page.indexOf('function MobileMusicRow'))
assert.match(mobileSupport, /Nothing recorded yet today/)
assert.doesNotMatch(mobileSupport, /Exercise Dex/)
assert.match(page, /progression\?\.totalXp\.toLocaleString/)
assert.match(page, /data\.gamification\.streak\.current/)
assert.match(page, /formatNumber\(data\.food\.kcal\)/)
assert.match(page, /Latest Achievement/)
assert.match(app, /<ProfileProvider>/)
assert.match(app, /<HomePage onNavigate=/)
assert.match(app, /<WorkoutPage key=\{`workout:/)
assert.match(app, /createNavigationHistory\(rootLocation\)/)
assert.doesNotMatch(appShell, /Offline ready/i)
assert.doesNotMatch(appShell, /MobileHomeThemeControls/)
assert.doesNotMatch(appShell, /<select aria-label="Faction"/)
assert.match(appShell, /useResolvedBrightness/)
assert.match(appShell, /setBrightness\(resolvedBrightness === 'dark' \? 'light' : 'dark'\)/)
assert.match(appShell, /<RetroGearIcon className="retro-gear-icon"/)
assert.match(appShell, /aria-label="Open settings"/)

assert.match(settings, /<legend>Faction<\/legend>/)
assert.match(settings, /Display Name <em/)
assert.match(settings, /Shown in your FitDex greeting/)
assert.match(settings, /Required/)
assert.match(settings, /maxLength=\{MAX_DISPLAY_NAME_LENGTH\}/)
assert.match(settings, /displayNameLength\(value\)/)
assert.match(settings, /Save Display Name/)
assert.doesNotMatch(settings, /SettingsPlaceholder number="08" title="Exercise Dex"/)
assert.doesNotMatch(settings, /Configuration coming in a future phase/)
assert.doesNotMatch(settings, /Phase 1A/)
assert.match(settings, /About FitDex/)
assert.match(settings, /Developed by/)
assert.match(settings, /Arijit Bhaduri/)
assert.match(settings, /Your FitDex fitness data is stored locally on your device/)
assert.match(settings, /APP_VERSION/)
assert.match(vite, /__FITDEX_APP_VERSION__.*packageVersion/s)
assert.match(packageJson.version, /^\d+\.\d+\.\d+$/)
assert.match(settings, /FITDEX \/\/ SYSTEM TERMINAL/)
assert.match(settings, /Personalize/)
assert.match(settings, /NUTRITION TARGETS/)
assert.doesNotMatch(settings, /SettingsPlaceholder|Coming later|Coming soon/)
assert.match(models, /displayName\?: string/)
assert.match(database, /DATABASE_SCHEMA_VERSION = 7/)
assert.doesNotMatch(database, /homeDashboard|homeSummary|dailyHomeState/)

assert.match(avatar, /loading=\{priority \? 'eager' : 'lazy'\}/)
assert.match(avatar, /fetchPriority=\{priority \? 'high' : 'auto'\}/)
assert.match(avatar, /width=\{384\}/)
assert.match(avatar, /height=\{576\}/)
assert.match(avatar, /imageStatus !== 'loaded'/)
assert.equal(AVATARS.length, 6)
for (const item of AVATARS) {
  const bytes = fs.readFileSync(`public${item.assetPath}`)
  assert.equal(bytes.toString('ascii', 1, 4), 'PNG')
  assert.equal(bytes.readUInt32BE(16), 384)
  assert.equal(bytes.readUInt32BE(20), 576)
  assert.ok(bytes.byteLength < 400_000, `${item.id} avatar should remain below 400 KB`)
}
assert.match(vite, /globPatterns: \['\*\*\/\*\.\{js,css,html,svg,png,woff2\}'\]/)
assert.doesNotMatch(vite, /mp4/)

assert.match(css, /\.home-hero-player \{[^}]*grid-template-columns: auto minmax\(0, 1fr\) auto/s)
assert.match(page, /home-command-home fitdex-page-frame/)
assert.match(page, /FitDex \/\/ Home Terminal/)
assert.match(page, /status-terminal-dot/)
assert.match(page, /<section className="home-command-hero">/)
assert.match(page, /home-command-hero[\s\S]*home-command-xp[\s\S]*HomeConsistencyRail/)
assert.match(css, /\.fitdex-page-frame \{[^}]*border: 4px solid var\(--color-border-strong\)/s)
assert.match(css, /@media \(max-width: 700px\)[\s\S]*\.app-main:has\(\.home-command-home\.fitdex-page-frame\) \{[^}]*border-inline: 0;[^}]*background: var\(--color-app-surface\)/s)
assert.match(css, /@media \(max-width: 700px\)[\s\S]*\.fitdex-page-frame \{[^}]*border-width: 2px;[^}]*box-shadow: 0 8px 24px var\(--color-shadow\)/s)
assert.match(css, /\.home-command-player \{[^}]*grid-template-columns: 66px minmax\(0, 1fr\) auto/s)
assert.match(css, /\.home-command-rank\s+\.gamification-badge\.is-small\s*\{[^}]*width:\s*42px;\s*height:\s*42px;/s)
assert.match(css, /\.home-command-menu\s*\{[^}]*display:\s*grid;[^}]*gap:\s*8px;[^}]*border:\s*0;/s)
assert.match(css, /\.home-hero-quest::before \{[^}]*background: var\(--color-hero-accent\)/s)
assert.match(css, /\.home-hero-player-copy \.eyebrow \{[^}]*color: var\(--color-hero-accent\)/s)
assert.match(css, /\.home-quest-actions \.primary-button \{[^}]*width: 100%/s)
assert.match(css, /\.home-hero-status \{[^}]*grid-template-columns: repeat\(3,/s)
assert.match(css, /\.home-desktop-hero,\s*\.home-desktop-workout,\s*\.home-desktop-content\s*\{[^}]*display:\s*none;\s*\}/s)
assert.match(css, /@media\s*\(min-width:\s*701px\)[\s\S]*\.home-mobile-hero\s*\{[^}]*display:\s*none;\s*\}/s)
assert.match(css, /@media \(min-width: 701px\)[\s\S]*\.home-desktop-hero \{[^}]*display: grid;/)
assert.doesNotMatch(css, /\.mobile-home-theme-controls/)
assert.doesNotMatch(css, /\.mobile-home-faction/)
assert.match(css, /\.battle-music-channel\s*\{[^}]*min-height:\s*50px;/s)
assert.match(css, /\.home-command-row,\s*\.home-command-music-row\s*\{[^}]*border-radius:\s*8px;/s)
assert.doesNotMatch(css, /\.home-hero\[data-faction='amazonians'\]/)
assert.doesNotMatch(page, /home-hero" data-faction/)
assert.match(themeCss, /--color-hero-accent: var\(--color-theme-accent\)/)
assert.match(themeCss, /\/\* Spartans light:[\s\S]*--color-primary: #1f8582/)
assert.match(themeCss, /\/\* Spartans dark:[\s\S]*--color-primary: #2e9895/)
assert.match(themeCss, /\/\* Amazonians dark:[\s\S]*--color-primary: #906390/)
assert.match(themeCss, /:root\[data-theme-family='amazonians'\] \{[\s\S]*--color-primary: #785178/)
assert.match(css, /\.home-quick-access \{[^}]*grid-template-columns: repeat\(2,/s)
assert.match(css, /\.home-week-grid \{[^}]*grid-template-columns: repeat\(7,/s)
assert.match(css, /\.home-music-controls \{[^}]*grid-template-columns: repeat\(4,/s)
assert.match(css, /\.home-music-tracks \{[^}]*grid-template-columns: repeat\(3,/s)
assert.match(css, /@media\s*\(max-width:\s*374px\)[\s\S]*\.home-meal-status\s*\{[^}]*grid-template-columns:\s*1fr;\s*\}/s)
assert.match(css, /\.display-name-form input \{[^}]*min-height: 48px;/s)
assert.match(css, /\.about-app-icon\s*\{[^}]*width:\s*48px;\s*height:\s*48px;/s)
assert.match(css, /\.about-copy p \{[^}]*overflow-wrap: anywhere;/s)
assert.match(page, /<HomeConsistencyRail data=\{data\}/)
assert.match(page, /function HomeConsistencyRail/)
assert.match(page, /home-consistency-rail-3cell/)
assert.match(page, /FreezeSnowflakeIcon/)
assert.match(page, /cell-primary/)
assert.match(page, /cell-freeze/)
assert.match(page, /cell-best/)
assert.match(page, /setGamificationView\('streak'\)/)
assert.match(page, /StreakDetailView data=\{data\.gamification\}/)
assert.match(css, /\.home-consistency-rail-3cell\s*\{[^}]*grid-template-columns:\s*1\.25fr 1fr 1fr 20px;/s)
assert.match(css, /\.home-consistency-rail-3cell\s*\{[^}]*height:\s*48px;/s)
assert.match(css, /\.freeze-snowflake-icon\s*\{[^}]*color:\s*var\(--color-primary-text\);/s)
assert.match(css, /@media\s*\(max-width:\s*340px\)[\s\S]*\.rail-cell\s*\{[^}]*padding:\s*3px 5px;/s)
assert.match(page, /unlockedCount\s*\?\s*`\$\{unlockedCount\} of 52 unlocked`\s*:\s*'52 badges to unlock'/)
assert.match(css, /\.home-command-hero\s*\{[^}]*border-radius:\s*11px;[^}]*linear-gradient/s)
assert.match(css, /\.home-command-caret\s*\{[^}]*width:\s*32px;[^}]*border-radius:\s*8px;/s)
assert.match(css, /\.home-command-state\s*\{[^}]*border-radius:\s*999px;/s)
assert.match(css, /\.home-command-row>\.home-command-number,\s*\.home-command-music-row \.home-command-number\s*\{[^}]*border-radius:\s*7px;/s)
assert.match(css, /\.home-command-hero \.home-command-player \.avatar-portrait\s*\{[^}]*overflow:\s*visible;[^}]*border:\s*0;[^}]*background:\s*transparent;[^}]*box-shadow:\s*none;/s)
assert.match(css, /:root\[data-theme-family='spartans'\]\[data-brightness='light'\] \.home-command-home\s*\{[\s\S]*--home-command-accent:\s*#147c7a;/)
assert.match(css, /:root\[data-theme-family='amazonians'\]\[data-brightness='dark'\] \.home-command-home\s*\{[\s\S]*--home-command-accent:\s*#d68ac4;/)
assert.match(css, /:root\[data-theme-family='amazonians'\]\[data-brightness='light'\] \.home-command-home\s*\{[\s\S]*--home-command-accent:\s*#a6538d;/)
assert.match(css, /\.home-command-hero \.home-hero-xp>i\s*\{\s*background:\s*var\(--home-command-accent\);/)
assert.match(css, /\.home-command-caret\s*\{[^}]*color:\s*var\(--home-command-accent\);/s)
assert.match(css, /\.home-command-home \.home-quest-actions \.primary-button\s*\{[^}]*background:[^}]*var\(--home-command-accent-strong\)[^}]*color:\s*var\(--home-command-accent-ink\);/s)

console.log('Home UI assertions passed: real dashboard sections, 3-cell consistency rail, navigation intents, local profile form, priority avatars, optimized assets, PWA safety, responsive classes, accessibility, and theme tokens')
