/// <reference types="node" />
import assert from 'node:assert/strict'
import fs from 'node:fs'

const page = fs.readFileSync('src/pages/ProgressPage.tsx', 'utf8')
const css = fs.readFileSync('src/styles/app.css', 'utf8')
const repository = fs.readFileSync('src/features/progress/progressRepository.ts', 'utf8')
const database = fs.readFileSync('src/data/database.ts', 'utf8')
const records = fs.readFileSync('src/features/progress/personalRecords.ts', 'utf8')

assert.match(page, /terminalTitle="FITDEX \/\/ PROGRESS TERMINAL"/)
assert.match(page, /CharacterHero/)
assert.ok(page.includes('rankAssetPath(progression.rank)'))
assert.match(page, /Lifetime XP/)
assert.match(page, /Rank Journey/)
assert.match(page, /Achievements/)
assert.doesNotMatch(page, /progress-view-tabs|role="tablist"|>Overview<|>Records</)
assert.match(page, /detailView, setDetailView\] = useState<'achievements' \| 'rank'>\(\)/)
assert.doesNotMatch(page, /setView\(|view === 'overview'|view === 'records'/)
assert.ok(page.includes('PROGRESS_PERIODS.map'))
assert.ok(page.includes('aria-pressed={period === item}'))
assert.match(page, /Training attributes/)
assert.match(page, /Real progress stats/)
assert.match(page, /buildWorkoutFrequencyTrend/)
assert.match(page, /buildVolumeTrend/)
assert.match(page, /buildNutritionTrend/)
assert.match(page, /Progress trend/)
assert.match(page, /View All PRs/)
assert.match(page, /setRecordsOpen\(true\)/)
assert.match(page, /onRank=\{\(\) => \{ playEffect\('select'\); setDetailView\('rank'\) \}\}/)
assert.match(page, /onAchievements=\{\(\) => \{ playEffect\('select'\); setDetailView\('achievements'\) \}\}/)
assert.ok(page.includes('records.slice(0, 3)'))
assert.match(page, /Nutrition/)
assert.match(page, /Start building your history/)
assert.match(page, /Progress unavailable/)
assert.match(page, /role="img" aria-label=/)
assert.match(page, /terminalTitle="FITDEX \/\/ RECORD BOOK"/)
assert.match(page, /Search personal records by exercise name/)
assert.match(page, /pr-meta-strip/)
assert.match(page, /pr-chapter-list/)
assert.match(page, /pr-chapter-card/)
assert.match(page, /pr-chapter-header/)
assert.match(page, /pr-chapter-accordion-body/)
assert.match(page, /proto-filter-sheet/)
assert.match(page, /Bodyweight \/ Reps/)
assert.ok(page.includes("category === 'weight'"))
assert.ok(page.includes("category === 'bodyweight_reps'"))
assert.ok(page.includes('openChapterId === chapter.id'))
assert.match(page, /pr-card/)
assert.match(page, /pr-badge-slot/)
assert.match(page, /pr-card-drawer/)
assert.match(page, /Back to Progress/)
assert.ok(page.includes("useBackNavigation('progress-subview'"))
assert.ok(page.includes('loadGamificationDashboard(referenceDateKey, reconcile)'))
assert.ok(page.includes("addEventListener('fitdex:gamification-changed', handleGamificationChanged)"))
assert.doesNotMatch(page, /estimated 1RM|body measurement|calorie target/i)
assert.ok(!page.includes('scrollIntoView') && !page.includes('scrollTo('))

assert.ok(repository.includes('[status+completedAt]'))
assert.ok(repository.includes("db.workoutExercises.where('workoutId').anyOf"))
assert.doesNotMatch(repository, /progressRecords|personalRecords|analyticsCache/)
assert.match(database, /DATABASE_SCHEMA_VERSION = 7/)
assert.doesNotMatch(database, /progressRecords|personalRecords|progressDaily|analyticsCache/)
assert.doesNotMatch(records, /1RM/i)

assert.ok(css.includes('.progress-character-hero {'))
assert.doesNotMatch(css, /progress-view-tabs/)
assert.ok(css.includes('.progress-attribute {'))
assert.ok(css.includes('.progress-trend-switch {'))
assert.match(css, /\.progress-pr-cta\s*\{[^}]*display:\s*flex;[^}]*width:\s*100%;[^}]*min-height:\s*52px;/s)
assert.match(css, /\.progress-chart\s*\{[^}]*display:\s*grid;[^}]*min-width:\s*0;[^}]*height:\s*190px;/s)
assert.match(css, /\.pr-meta-strip\s*\{[^}]*display:\s*flex;[^}]*justify-content:\s*space-between;/s)
assert.match(css, /\.pr-chapter-header\s*\{[^}]*display:\s*grid;[^}]*grid-template-columns:\s*auto\s*minmax\(0,\s*1fr\)\s*auto;/s)
assert.match(css, /\.pr-chapter-accordion-body\s*\{[^}]*display:\s*flex;/s)
assert.match(css, /\.pr-card-main\s*\{[^}]*grid-template-columns:\s*auto\s*minmax\(0,\s*1fr\)\s*auto;/s)
assert.match(css, /\.pr-card\s*\{[^}]*var\(--color-surface-raised\)/s)
assert.match(css, /\.pr-badge-slot\s*\{/s)
assert.match(css, /\.pr-card-drawer\s*\{/s)
assert.match(css, /\.pr-submetric-grid\s*\{[^}]*grid-template-columns:\s*repeat\(auto-fit,\s*minmax\(min\(100%,\s*200px\),\s*1fr\)\);/s)
assert.match(css, /\.proto-filter-sheet\s*\{/s)

console.log('Progress V3 UI assertions passed: character hero, source-backed attributes, trend switch, C2 Chapter Accordion Record Book archive, empty states, accessibility, responsive tokens, and no scroll reset')
