/// <reference types="node" />
import assert from 'node:assert/strict'
import fs from 'node:fs'

const settings = fs.readFileSync('src/features/settings/SettingsPage.tsx', 'utf8')
const food = fs.readFileSync('src/pages/FoodPage.tsx', 'utf8')
const repository = fs.readFileSync('src/features/nutritionTargets/nutritionTargetRepository.ts', 'utf8')
const gamification = fs.readFileSync('src/features/gamification/gamificationRepository.ts', 'utf8')
const achievements = fs.readFileSync('src/features/gamification/achievementCatalog.ts', 'utf8')
const dailyTargetsCard = food.slice(food.indexOf('function DailyTargetsCard'), food.indexOf('function TargetsOffCard'))

assert.match(settings, /Nutrition Targets/)
assert.match(settings, /Target Engine/)
assert.match(settings, /control-bay-engine-readout/)
assert.match(settings, /Target Calculation \{targets\.enabled \? 'Ready' : 'Paused'\}/)
assert.match(settings, /<ControlBayStatus online=\{targets\.enabled\}>\{targets\.enabled \? 'Online' : 'Standby'\}<\/ControlBayStatus>/)
assert.match(settings, /Baseline Parameters/)
assert.match(settings, /Goal Mode/)
assert.match(settings, /Energy Accounting/)
assert.match(settings, /Daily Targets/)
assert.match(settings, /Daily Calorie Target/i)
assert.match(settings, /Daily Protein Target/i)
assert.match(settings, /Protein Target: Not Set/i)
assert.match(settings, /RECALCULATE \(\{suggestedProtein\}g\)/)
assert.match(settings, /UNSET/)
assert.doesNotMatch(settings, /⚡\s*Recalculate/i)
assert.match(settings, /control-bay-protein-action is-recalc/)
assert.match(settings, /control-bay-protein-action is-unset/)
assert.doesNotMatch(settings, /(?:carb|fat|fiber) target/i)
assert.match(settings, /Save Targets/)
// Confirm no internal TDEE multipliers leaked in options
assert.doesNotMatch(settings, /<option[^>]*>.*?·\s*1\.\d+/i)
// Confirm no decorative RECORD numbering
assert.doesNotMatch(settings, /RECORD\s*0[1-3]/i)
assert.match(settings, /NutritionTargetDraft/)
assert.match(settings, /NumericTargetControl/)
assert.match(settings, /value=\{draft\.age\}/)
assert.match(settings, /parseNutritionTargetDraft/)
assert.match(food, /Daily targets/)
assert.match(dailyTargetsCard, /TargetMetric label="Calories"/)
assert.match(dailyTargetsCard, /TargetMetric label="Protein"/)
assert.doesNotMatch(dailyTargetsCard, /TargetMetric label="(?:Carbs|Fat|Fiber)"/)
assert.match(food, /target-status-dialog/)
assert.match(food, /onOpenSettings/)
assert.match(repository, /nutritionTargetsInitializedAt/)
assert.match(repository, /nutritionTargetsEligibleFrom/)
assert.match(food, /liveQuery\(loadNutritionTargets\)/)
assert.doesNotMatch(gamification, /(?:carb|fat|fiber)_target/)
assert.doesNotMatch(achievements, /(?:carb|fat|fiber)-target/)
const appCss = fs.readFileSync('src/styles/app.css', 'utf8')

// Daily source states are a shared retro status rail with internal divider.
assert.match(settings, /control-bay-source-rail/)
assert.match(settings, /control-bay-source-cell \$\{targets\.calorieTargetSource === 'calculated' \? 'source-calc' : 'source-manual'\}/)
assert.match(settings, /control-bay-source-cell \$\{isProteinUnset \? 'protein-unset' : proteinSource === 'calculated' \? 'source-calc' : 'source-manual'\}/)
assert.match(appCss, /\.control-bay-targets \.control-bay-source-rail\s*\{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);/s)
assert.match(appCss, /\.control-bay-targets \.control-bay-source-cell\s*\+\s*\.control-bay-source-cell\s*\{[^}]*border-left: 1px solid var\(--color-border\);/s)
assert.match(appCss, /\.control-bay-targets \.control-bay-apply-key\s*\{[^}]*margin: 8px auto 0;/s)

// Control Bay telemetry remains four equal hardware wells with function key below.
assert.match(settings, /control-bay-telemetry-grid/)
assert.match(settings, /<span className="control-bay-label">RMR<\/span><strong>\{rmr\}/)
assert.match(settings, /<span className="control-bay-label">TDEE<\/span><strong>\{tdee\}/)
assert.match(settings, /<span className="control-bay-label">Goal<\/span><strong>\{suggestions\?\.defaultTarget \?\? 0\}/)
assert.match(settings, /<span className="control-bay-label">Protein<\/span><strong>\{suggestedProtein\}/)
assert.match(settings, /className="recom-chip control-bay-apply-key"/)
assert.match(settings, /Apply Calculated \{suggestions\.defaultTarget\} kcal/)
assert.match(appCss, /\.control-bay-targets \.control-bay-telemetry-grid\s*\{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);/s)
assert.match(settings, /className="profile control-bay-profile-stack"/)
assert.match(appCss, /\.control-bay-targets \.profile,\s*\.control-bay-targets \.control-bay-profile-stack\s*\{[^}]*grid-template-columns: minmax\(0, 1fr\);/s)
assert.match(settings, /control-bay-key-cluster/)
assert.match(settings, /control-bay-physical-key-bank control-bay-goal-key-bank/)
assert.match(settings, /control-bay-physical-key-bank control-bay-sex-key-bank/)
assert.match(appCss, /\.control-bay-targets \.control-bay-key-cluster\s*\{ display: flex; justify-content: center;/)
assert.match(appCss, /\.control-bay-targets \.control-bay-goal-key-bank \{ grid-template-columns: repeat\(3, minmax\(0, 1fr\)\); \}/)
assert.match(appCss, /\.control-bay-targets \.control-bay-sex-key-bank \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); \}/)
assert.match(appCss, /\.control-bay-targets \.calc-row,\s*\.control-bay-targets \.control-bay-stepper\s*\{[^}]*grid-template-columns: 28px minmax\(0, 1fr\) 28px;[^}]*gap: 4px;/s)
assert.match(appCss, /\.control-bay-targets \.lcd\s*\{[^}]*height: 28px;/s)
assert.match(settings, /className="target-programmer control-bay-calorie-stepper"/)
assert.match(appCss, /\.control-bay-targets \.calc-key,\s*\.control-bay-targets \.stepper-btn,\s*\.control-bay-targets \.control-bay-stepper > button[\s\S]*?width: 28px;[\s\S]*?height: 28px;/s)
assert.match(appCss, /\.control-bay-targets \.target-programmer \.lcd-input,[\s\S]*?-webkit-appearance: none;[\s\S]*?appearance: textfield;/s)
assert.match(appCss, /\.control-bay-targets \.target-programmer \.lcd-input::-webkit-inner-spin-button,[\s\S]*?-webkit-appearance:\s*none;\s*appearance:\s*none;/s)
assert.match(settings, /id="nutrition-baseline"/)
assert.match(settings, /id="nutrition-energy"/)
assert.match(settings, /id="nutrition-daily"/)
assert.match(settings, /defaultExpanded=\{false\}/)
assert.match(appCss, /\.control-bay-status\.is-online \{ color: var\(--color-success\); \}/)

// Audio SFX coverage assertions
assert.match(settings, /const \{ playEffect \} = useAudio\(\)/)
assert.match(settings, /onClick=\{\(\) => \{\s*playEffect\('select'\);\s*update\('enabled', true\)\s*\}\}/)
assert.match(settings, /onClick=\{\(\) => \{\s*playEffect\('select'\);\s*update\('enabled', false\)\s*\}\}/)
assert.match(settings, /onClick=\{\(\) => \{\s*playEffect\('select'\);\s*update\('goal', goal\)\s*\}\}/)
assert.match(settings, /update\('sex', sex\)/)
assert.match(settings, /onChange=\{\(event\) => \{\s*playEffect\('select'\)\s*const act = event\.target\.value/)
assert.match(settings, /onClick=\{\(\) => \{\s*playEffect\('select'\);\s*applyCalorie\(/)
assert.match(settings, /stepCalorie = \(delta: number\) => \{\s*playEffect\('select'\)/)
assert.match(settings, /stepProtein = \(delta: number\) => \{\s*playEffect\('select'\)/)
assert.match(settings, /await saveNutritionTargets\(\{ \.\.\.targets, \.\.\.parsed \}\)[\s\S]*?playEffect\('add'\)/)

// Containment assertions: Nutrition Codex sits directly in PageFrame without duplicate/rogue settings-detail-card outer border
assert.doesNotMatch(settings, /(?:nutrition-codex-container|v3-ledger|v3-row|terminal-stepper|cmd-binary)/)
assert.doesNotMatch(appCss, /(?:nutrition-codex-container|control-bay-profile-grid)/)

console.log('Nutrition targets UI assertions passed: Control Bay layout, calorie/protein-only targets, tracked-only macros, Settings management, Food card, status detail, forward-only activation, select SFX, add SFX on save, and PageFrame containment')
