/// <reference types="node" />
import 'fake-indexeddb/auto'
import assert from 'node:assert/strict'
import Dexie from 'dexie'
import fs from 'node:fs'
import { AUDIO_EFFECT_PATHS, AUDIO_EFFECT_PRIORITY, BACKGROUND_MUSIC_PATHS, DEFAULT_AUDIO_PREFERENCES, cycleBackgroundTrack, evaluateGamificationAudioTransition, foodSaveEffect, highestPriorityEffect, resolveAudioPreferences } from './audioModel.ts'

assert.deepEqual(DEFAULT_AUDIO_PREFERENCES, { soundEffectsEnabled: true, backgroundMusic: 'none' })
assert.deepEqual(resolveAudioPreferences(), DEFAULT_AUDIO_PREFERENCES)
assert.deepEqual(resolveAudioPreferences({}), DEFAULT_AUDIO_PREFERENCES, 'old Settings records remain valid')
assert.deepEqual(resolveAudioPreferences({ soundEffectsEnabled: false, backgroundMusic: 'villain' }), { soundEffectsEnabled: false, backgroundMusic: 'villain' })
assert.deepEqual(AUDIO_EFFECT_PATHS, {
  select: '/audio/select.mp3', add: '/audio/add.mp3', achievement_unlock: '/audio/achievements_unlock.mp3', progress_complete: '/audio/progress_complete.mp3',
})
assert.deepEqual(BACKGROUND_MUSIC_PATHS, { warrior: '/audio/bgm1.mp3', hardened: '/audio/bgm2.mp3', villain: '/audio/bgm3.mp3' })
assert.deepEqual(AUDIO_EFFECT_PRIORITY, ['achievement_unlock', 'progress_complete', 'add', 'select'])
assert.equal(highestPriorityEffect(['select', 'add', 'progress_complete', 'achievement_unlock']), 'achievement_unlock')
assert.equal(highestPriorityEffect(['select', 'add', 'progress_complete']), 'progress_complete')
assert.equal(foodSaveEffect(false, 0), 'progress_complete')
assert.equal(foodSaveEffect(false, 1), 'add')
assert.equal(foodSaveEffect(true, 0), undefined)
assert.equal(cycleBackgroundTrack('warrior', 1), 'hardened')
assert.equal(cycleBackgroundTrack('hardened', 1), 'villain')
assert.equal(cycleBackgroundTrack('villain', 1), 'warrior')
assert.equal(cycleBackgroundTrack('warrior', -1), 'villain')
const silentRestore = evaluateGamificationAudioTransition('', { levelUp: false, afterLevel: 1, unlockIds: ['first-workout'] }, false)
assert.equal(silentRestore.play, false, 'existing app-launch transitions stay silent')
assert.equal(evaluateGamificationAudioTransition(silentRestore.signature, { levelUp: false, afterLevel: 1, unlockIds: ['first-workout'] }, true).play, false, 'repeat reconciliation stays silent')
const newUnlock = evaluateGamificationAudioTransition(silentRestore.signature, { levelUp: false, afterLevel: 1, unlockIds: ['first-workout', '10-workouts'] }, true)
assert.equal(newUnlock.play, true)
assert.equal(evaluateGamificationAudioTransition(newUnlock.signature, { levelUp: false, afterLevel: 1, unlockIds: ['first-workout', '10-workouts'] }, true).play, false)
assert.equal(evaluateGamificationAudioTransition(newUnlock.signature, { levelUp: true, afterLevel: 2, unlockIds: ['first-workout', '10-workouts'] }, true).play, true)

for (const path of [...Object.values(AUDIO_EFFECT_PATHS), ...Object.values(BACKGROUND_MUSIC_PATHS)]) assert.ok(fs.existsSync(`public${path}`), `missing audio asset: ${path}`)

const provider = fs.readFileSync('src/features/audio/AudioProvider.tsx', 'utf8')
const settingsUi = fs.readFileSync('src/features/settings/SettingsPage.tsx', 'utf8')
const app = fs.readFileSync('src/app/App.tsx', 'utf8')
const workout = fs.readFileSync('src/features/workout/WorkoutSessionViews.tsx', 'utf8')
const food = fs.readFileSync('src/pages/FoodPage.tsx', 'utf8')
const gamification = fs.readFileSync('src/features/gamification/GamificationViews.tsx', 'utf8')
assert.match(provider, /bgm\.loop = true/)
assert.match(provider, /bgm\.pause\(\)[\s\S]*bgm\.src = nextSource/)
assert.match(provider, /preference === 'none'[\s\S]*bgm\.pause\(\)/)
assert.match(provider, /visibilitychange/)
assert.match(provider, /pointerdown/)
assert.match(provider, /pauseBackgroundMusic\(\)/)
assert.match(provider, /resumeBackgroundMusic\(\)/)
assert.match(provider, /setBackgroundMusicPaused\(false\)[\s\S]*setBackgroundMusicState\(preference\)/)
assert.match(provider, /play\(\)[\s\S]*catch/)
assert.match(app, /<AudioProvider>[\s\S]*<BackNavigationProvider>[\s\S]*<App \/>/)
assert.match(settingsUi, /Sound Effects/)
assert.match(settingsUi, /UI and progress sounds/)
assert.match(settingsUi, /Background Music/)
for (const label of ['Warrior', 'Hardened', 'Villain', 'No Music']) assert.match(settingsUi, new RegExp(label))
assert.match(settingsUi, /type="checkbox" checked=\{soundEffectsEnabled\}/)
assert.match(settingsUi, /type="radio" name="background-music"/)
assert.match(workout, /finishWorkout\(workoutId\)\.then\(\(\) => \{ playEffect\('progress_complete'\); onCompleted/)
assert.match(workout, /catch\(async \(error: unknown\)/, 'blocked or failed completion does not request completion audio')
assert.match(food, /const beforeCount = \(await listMealEntries\(date, meal\)\)\.length/)
assert.match(food, /if \(editing\) await editFoodLog/)
assert.match(gamification, /refresh\(false\)/, 'app-load notification check stays silent')
assert.match(gamification, /handleGamificationChanged = \(\) => refresh\(true\)/)
assert.match(gamification, /evaluateGamificationAudioTransition/)

await Dexie.delete('fitdex')
const { db } = await import('../../data/database.ts')
const { loadAudioPreferences, saveBackgroundMusic, saveSoundEffectsEnabled } = await import('./audioRepository.ts')
await db.settings.put({ id: 'settings', createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z' })
assert.deepEqual(await loadAudioPreferences(), DEFAULT_AUDIO_PREFERENCES)
await saveSoundEffectsEnabled(false)
await saveBackgroundMusic('hardened')
assert.deepEqual(await loadAudioPreferences(), { soundEffectsEnabled: false, backgroundMusic: 'hardened' })
db.close()
await Dexie.delete('fitdex')

console.log('Audio tests passed: assets, defaults/persistence, mappings, priority, meal transitions, provider behavior, Settings controls, and completion/unlock wiring')
