/// <reference types="node" />
import assert from 'node:assert/strict'
import fs from 'node:fs'
import { customCategoryCssColor, resolveCustomCategoryColor } from './foodModel.ts'

const page = fs.readFileSync('src/pages/FoodPage.tsx', 'utf8')
const css = fs.readFileSync('src/styles/app.css', 'utf8')
const themeCss = fs.readFileSync('src/index.css', 'utf8')
const icons = fs.readFileSync('src/features/food/FoodIcons.tsx', 'utf8')
const model = fs.readFileSync('src/features/food/foodModel.ts', 'utf8')
const repository = fs.readFileSync('src/features/food/foodRepository.ts', 'utf8')
const pwa = fs.readFileSync('vite.config.ts', 'utf8')
const localDate = fs.readFileSync('src/utils/localDate.ts', 'utf8')

// Phase 3A locked Goal-First daily hub.
assert.match(page, /data-food-design="goal-first"/)
assert.match(page, /Daily command/)
assert.match(page, /Calories and protein/)
assert.match(page, /TargetMetric label="Calories"/)
assert.match(page, /TargetMetric label="Protein"/)
assert.match(page, /targets\?\.enabled && targets\.calorieTarget > 0 \? <DailyTargetsCard/)
assert.match(page, /TargetsOffCard/)
assert.match(page, /proteinTargetUsable = Number\.isFinite\(targets\.proteinTargetGrams\) && targets\.proteinTargetGrams > 0/)
assert.match(page, /usableTarget \? Math\.min\(100, Math\.max\(0, \(current \/ target\) \* 100\)\) : 0/)
assert.match(page, /Target unavailable/)
assert.match(page, /entries\.length === 1 \? '1 Meal item logged' : `\$\{entries\.length\} Meal items logged`/)
assert.doesNotMatch(page, /id="food-meals-title">Meals<\/span>/)
assert.doesNotMatch(page, /Meals\d+ items logged/)
assert.match(page, /CANONICAL_MEAL_ORDER\.map/)
assert.match(model, /breakfast: 'Breakfast', lunch: 'Lunch', supper: 'Supper', dinner: 'Dinner'/)
assert.match(page, /Nutrition Details/)
assert.match(page, /CollapsibleModule[\s\S]*?id="food-macros"/)
assert.match(page, /\['carbs', 'Carbs', 'g'\], \['fat', 'Fat', 'g'\], \['fiber', 'Fiber', 'g'\]/)
assert.match(page, /Nutrition breakdown/i)
assert.match(page, /food-breakdown-switch/)
assert.match(page, /className="food-donut"[\s\S]*role="img"/)
assert.match(page, /evaluateCalorieDay/)
assert.match(page, /evaluateProteinDay/)
assert.match(page, /liveQuery\(loadNutritionTargets\)/)
assert.match(page, /onOpenSettings/)
assert.match(page, /setEntriesLoading\(true\)/)
assert.match(page, /<RetroLoader label="LOADING NUTRITION\.\.\." \/>/)
assert.match(page, /Previous day/)
assert.match(page, /Next day/)
assert.match(page, /disabled=\{isLocalToday\(date\)\}/)
assert.match(localDate, /date\.getFullYear\(\)/)
assert.doesNotMatch(localDate, /toISOString/)

// Phase 3B locked Compact discovery, editor, and category sheets.
assert.match(page, /Searches foods remembered on this device/)
assert.match(page, /title="Recent"/)
assert.match(page, /title="Frequent"/)
assert.match(page, /frequent\.filter\(\(food\) => !recentIds\.has\(food\.id\)\)/)
assert.match(page, /Quick Log/)
assert.match(page, /addFoodLog\(date, meal, rememberedFoodDraft\(food\)\)/)
assert.match(page, /Stored nutrition snapshot logged unchanged/)
assert.match(page, /Create New Food/)
assert.match(page, /Core nutrition/)
assert.match(page, /More Nutrition/)
assert.match(page, /NutritionInput field="(?:fiber|sugar|saturatedFat|sodium)"/)
assert.match(page, /Food name is required/)
assert.match(page, /cannot be negative/)
assert.match(page, /Remembered defaults stay unchanged/)
assert.match(page, /Saved remembered-food defaults stay unchanged/)
assert.match(page, /Delete Food Entry\?/)
assert.doesNotMatch(page, /window\.confirm/)
assert.match(page, /Delete Category\?/)
assert.match(page, /Remembered foods in this category will also be removed\. Historical food logs remain and become Uncategorized\./)
assert.match(page, /entry\.categoryKind === 'unresolved' \? 'Uncategorized'/)
assert.match(page, /role="alertdialog"/)
assert.match(page, /useBackNavigation\('food-entry-delete',[\s\S]*, 50\)/)
assert.match(page, /useBackNavigation\('food-category-delete',[\s\S]*, 70\)/)
assert.match(page, /useBackNavigation\('food-category-create',[\s\S]*, 60\)/)
assert.match(page, /useBackNavigation\('food-category-sheet',[\s\S]*, 50\)/)
assert.match(page, /document\.body\.style\.overflow = 'hidden'/)
assert.match(page, /className="food-category-content"/)
assert.match(page, /food-standard-categories/)
assert.match(page, /food-custom-categories/)
assert.match(page, /food-create-category/)
assert.match(page, /useBackNavigation\('food-editor',[\s\S]*, 20\)/)
assert.match(page, /foodSaveEffect\(false, beforeCount\)/)
assert.match(page, /playEffect\('select'\)/)

// Existing persistence/category contracts remain wired through production repositories.
assert.match(repository, /export async function deleteCustomFoodCategory/)
assert.match(repository, /db\.rememberedFoods\.bulkDelete/)
assert.match(repository, /entry\.categoryKind = 'unresolved'/)
assert.match(repository, /Predefined food categories cannot be deleted/)
assert.match(model, /if \(value\.trim\(\) === ''\) return undefined/)
assert.match(icons, /\/food\/meals\/meal-\$\{meal\}\.webp/)
assert.match(icons, /\/food\/categories\/category-\$\{categoryId\}\.webp/)
assert.match(icons, /CUSTOM_CATEGORY_ICON_ASSET_PATH = '\/food\/categories\/category-other\.webp'/)
assert.match(page, /PREDEFINED_FOOD_CATEGORIES\.map/)
assert.match(page, /CUSTOM_CATEGORY_COLORS\.map/)
assert.match(page, /Live icon preview/)
assert.match(page, /<CustomFoodCategoryIcon label=\{name\.trim\(\) \|\| 'Custom category'\} color=\{color\} \/>/)
assert.match(page, /onSelect\('other', category\.id, category\.name, category\.color\)/)
assert.doesNotMatch(page, /🍳|🍗|🍚|🥗/u)

assert.ok(fs.existsSync('public/food/categories/category-flour-wheat.webp'))
assert.ok(fs.existsSync('public/food/categories/category-other.webp'))
assert.equal(resolveCustomCategoryColor('amber'), 'amber')
assert.equal(resolveCustomCategoryColor('violet'), 'violet')
assert.equal(resolveCustomCategoryColor('invalid'), undefined)
assert.equal(customCategoryCssColor('amber'), 'var(--food-custom-amber)')
assert.equal(customCategoryCssColor('invalid'), 'var(--color-metal)')

const customColorValues = {
  amber: '#a86b08', coral: '#b85c43', crimson: '#a93d52', plum: '#805080', violet: '#6958a8',
  blue: '#326da8', teal: '#247b78', green: '#487d49', olive: '#74733a', slate: '#596773',
}
assert.equal(Object.keys(customColorValues).length, 10)
assert.equal(new Set(Object.values(customColorValues)).size, 10)
for (const [token, value] of Object.entries(customColorValues)) {
  assert.match(themeCss, new RegExp(`--food-custom-${token}: ${value};`))
  assert.equal(customCategoryCssColor(token), `var(--food-custom-${token})`)
}

// Responsive, accessible, token-based presentation.
assert.match(page, /terminalTitle="FITDEX \/\/ NUTRITION TERMINAL"/)
assert.match(page, /const terminalMeta = `\$\{gamification \? `LV \$\{gamification\.progression\.level\} · ` : ''\}\$\{terminalDate\.toLocaleDateString\(undefined, \{ weekday: 'short', day: '2-digit', month: 'short' \}\)\.replace\(\/,\/g, ''\)\.toUpperCase\(\)\}`/)
assert.match(page, /terminalMeta=\{terminalMeta\}/)
assert.doesNotMatch(page, /terminalMeta=\{`\$\{isLocalToday\(date\)/)
assert.match(page, /food-today-button/)
assert.match(page, /workout-hub-help/)
assert.match(css, /\.food-page \{[^}]*container: food-phase3 \/ inline-size/s)
assert.match(css, /\.food-goal-grid \{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/s)
assert.match(page, /className="food-list compact-list"/)
assert.match(page, /className="food-row"/)
assert.match(page, /className="food-select"/)
assert.match(page, /className="quick-log"/)
assert.match(page, /className="edit-button"/)
assert.match(css, /\.compact-list\s+\.food-row,\s*\.food-suggestion-row\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+62px\s+44px/s)
assert.match(css, /\.compact-list\s+\.food-select,\s*\.food-suggestion-select\s*\{[^}]*min-height:\s*58px/s)
assert.match(css, /\.compact-list\s+\.quick-log,\s*\.food-quick-log\s*\{[^}]*min-height:\s*58px/s)
assert.match(css, /\.compact-list\s+\.edit-button,\s*\.food-edit-remembered\s*\{[^}]*min-height:\s*58px/s)
assert.match(css, /\.food-dialog \{[^}]*100dvh[^}]*overflow-y: auto[^}]*overscroll-behavior: contain/s)
assert.match(css, /\.food-category-dialog \{[^}]*grid-template-rows: auto minmax\(0, 1fr\);[^}]*overflow: hidden/s)
assert.match(css, /\.food-category-content \{[^}]*min-height: 0;[^}]*overflow-x: hidden;[^}]*overflow-y: auto;[^}]*overscroll-behavior: contain/s)
assert.match(css, /\.category-grid \{[^}]*repeat\(auto-fit, minmax\(min\(158px, 100%\), 1fr\)\)/s)
assert.match(css, /\.food-sprite \{[^}]*position: relative;[^}]*overflow: hidden/s)
assert.match(css, /\.food-sprite img \{[^}]*width: 100%;[^}]*height: 100%;[^}]*grid-area: 1 \/ 1;[^}]*object-fit: contain/s)
assert.match(css, /@container\s*food-phase3\s*\(max-width:\s*350px\)[\s\S]*\.food-goal-grid\s*\{[^}]*grid-template-columns:\s*1fr;\s*\}/s)
assert.match(css, /@container\s*food-phase3\s*\(max-width:\s*350px\)[\s\S]*\.compact-list\s+\.food-row,\s*\.food-suggestion-row\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+58px\s+44px;\s*\}/s)
assert.match(css, /@media \(hover: hover\) and \(pointer: fine\)/)
assert.match(css, /@media \(prefers-reduced-motion: reduce\)/)
assert.match(css, /var\(--color-primary\)/)
assert.match(css, /\.food-search:focus-within\s*\{[^}]*border-color:\s*var\(--color-focus\)/s)
assert.match(css, /\.food-entry-copy h2 \{[^}]*overflow-wrap: anywhere/s)
assert.match(css, /\.category-grid button span:last-child \{[^}]*overflow-wrap: anywhere/s)
assert.match(pwa, /globPatterns: \['\*\*\/\*\.\{js,css,html,svg,png,woff2\}'\]/)
assert.doesNotMatch(pwa, /webp/)

// Approved Meal Detail secondary screen layout & structure assertions
assert.match(page, /terminalTitle="FITDEX \/\/ FOOD LOG"/)
assert.match(page, /className="proto-subhead"/)
assert.match(page, /‹ FOOD/)
assert.match(page, /food-meal-totals-module/)
assert.match(page, /proto-meal-slot/)
assert.match(page, /proto-meal-art/)
assert.match(page, /proto-status/)
assert.match(page, /className="proto-data"/)
assert.match(page, /CARBS.*FAT.*FIBER/s)
assert.match(page, /className="proto-secondary-nutrients"/)
assert.match(page, /Sugar.*Sat fat.*Sodium/s)
assert.match(page, /food-meal-entries-module/)
assert.match(page, /food-meal-selector/)
assert.match(page, /CANONICAL_MEAL_ORDER/)
assert.match(page, /proto-card-stack/)
assert.match(page, /proto-food-entry-card/)
assert.match(page, /EDIT/)
assert.match(page, /food-meal-action-module/)
assert.match(page, /food-add-action-btn/)
assert.match(page, /proto-meal-empty-state/)
assert.match(page, /proto-meal-empty-slot/)
assert.match(page, /NO FOOD LOGGED/)
assert.match(css, /\.proto-subhead\s*\{/s)
assert.match(css, /\.proto-module\s*\{/s)
assert.match(css, /\.proto-module\.is-primary\s*\{/s)
assert.match(css, /\.proto-meal-head\s*\{[^}]*grid-template-columns:\s*auto minmax\(0,\s*1fr\)/s)
assert.match(css, /\.proto-meal-slot\s*\{[^}]*width:\s*48px;[^}]*height:\s*48px;/s)
assert.match(css, /\.proto-meal-art\s*\{/s)
assert.match(css, /\.proto-data\s*\{[^}]*grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\)/s)
assert.match(css, /\.proto-tabs\s*\{[^}]*grid-template-columns:\s*repeat\(4,\s*minmax\(0,\s*1fr\)\)/s)
assert.match(css, /\.proto-food-entry-card\s*\{/s)
assert.match(css, /\.proto-meal-empty-state\s*\{/s)
assert.match(css, /\.proto-meal-empty-slot\s*\{[^}]*width:\s*40px;[^}]*height:\s*40px;/s)

console.log('Food UI assertions passed: Goal-First hub, Compact logging, Meal Detail prototype hierarchy, preserved persistence, responsive layout, and accessibility')
