/// <reference types="node" />
import 'fake-indexeddb/auto'
import assert from 'node:assert/strict'
import Dexie from 'dexie'
import { db } from '../../data/database.ts'
import { addFoodLog, createCustomCategory, deleteCustomFoodCategory, deleteFoodLog, editFoodLog, getDailyTotals, getFrequentFoods, getMealTotals, getRecentFoods, listFoodEntries, listMealEntries, searchRememberedFoods, updateCustomCategory } from './foodRepository.ts'
import { normalizeFoodName, parseOptionalNutrition, PREDEFINED_FOOD_CATEGORIES, validateNutrition } from './foodModel.ts'

await db.close()
await Dexie.delete('fitdex')
await db.open()

const date = '2026-08-23'
const nextDate = '2026-08-24'
const breakfast = await addFoodLog(date, 'breakfast', { name: 'Chicken Breast', categoryId: 'chicken', kcal: 330, protein: 62, carbs: 0, fat: 7.5, fiber: 0, sugar: 0, saturatedFat: 2.1, sodium: 175.5 })
await addFoodLog(date, 'lunch', { name: 'Brown Rice', categoryId: 'grains-rice', kcal: 216.5, protein: 5, carbs: 44.8, fat: 1.8, fiber: 3.5 })
await addFoodLog(date, 'supper', { name: 'Apple', categoryId: 'fruits', kcal: 95, carbs: 25, fiber: 4.4, sugar: 19 })
await addFoodLog(date, 'dinner', { name: 'Salmon', categoryId: 'fish-seafood', kcal: 280, protein: 39, fat: 13, saturatedFat: 3, sodium: 90 })
await addFoodLog(nextDate, 'breakfast', { name: 'Eggs', categoryId: 'eggs', kcal: 140, protein: 12, carbs: 1, fat: 10 })

assert.equal((await listFoodEntries(date)).length, 4)
for (const meal of ['breakfast', 'lunch', 'supper', 'dinner'] as const) assert.equal((await listMealEntries(date, meal)).length, 1)
assert.equal((await listFoodEntries(nextDate)).length, 1)
const totals = await getDailyTotals(date)
assert.deepEqual(totals, { kcal: 921.5, protein: 106, carbs: 69.8, fat: 22.3, fiber: 7.9, sugar: 19, saturatedFat: 5.1, sodium: 265.5 })
assert.deepEqual(await getMealTotals(date, 'breakfast'), { kcal: 330, protein: 62, carbs: 0, fat: 7.5, fiber: 0, sugar: 0, saturatedFat: 2.1, sodium: 175.5 })

const memory = await db.rememberedFoods.where('normalizedName').equals('chicken breast').first()
assert.ok(memory)
assert.equal(memory.categoryId, 'chicken')
assert.equal(memory.kcal, 330)
assert.equal(memory.timesUsed, 1)
await addFoodLog(date, 'lunch', { name: '  CHICKEN  BREAST ', categoryId: 'meat', kcal: 660, protein: 124 })
const reused = await db.rememberedFoods.where('normalizedName').equals('chicken breast').first()
assert.equal(await db.rememberedFoods.where('normalizedName').equals('chicken breast').count(), 1)
assert.equal(reused?.timesUsed, 2)
assert.equal(reused?.kcal, 330, 'A changed portion must not rewrite remembered defaults')
assert.equal(reused?.categoryId, 'chicken', 'A one-off selection must not rewrite remembered category')
assert.equal(reused?.mealUsage.breakfast, 1)
assert.equal(reused?.mealUsage.lunch, 1)

assert.equal(normalizeFoodName('Chicken Breast'), 'chicken breast')
assert.equal(normalizeFoodName('chicken breast'), 'chicken breast')
assert.equal(normalizeFoodName('CHICKEN  BREAST'), 'chicken breast')
assert.equal(normalizeFoodName('Chicken-Breast'), 'chicken breast')
assert.notEqual(normalizeFoodName('Chicken Curry'), normalizeFoodName('Chicken Breast'))
assert.equal((await searchRememberedFoods('CHI', 'breakfast'))[0]?.id, memory.id)
assert.equal((await searchRememberedFoods('chicken---breast', 'breakfast'))[0]?.id, memory.id)

await addFoodLog(date, 'breakfast', { name: 'Oats', categoryId: 'grains-rice', kcal: 150 })
await addFoodLog(nextDate, 'breakfast', { name: 'Oats', categoryId: 'grains-rice', kcal: 300 })
await addFoodLog(nextDate, 'breakfast', { name: 'Oats', categoryId: 'grains-rice', kcal: 150 })
assert.equal((await getRecentFoods('breakfast'))[0]?.name, 'Oats')
assert.equal((await getFrequentFoods('breakfast'))[0]?.name, 'Oats')
assert.equal((await getRecentFoods('dinner')).some((food) => food.name === 'Salmon'), true)

const custom = await createCustomCategory('Homemade Curry', 'amber')
const duplicateCustom = await createCustomCategory(' homemade  curry ', 'blue')
assert.equal(duplicateCustom.id, custom.id)
const coralCategory = await createCustomCategory('Coral preview save', 'coral')
assert.equal(coralCategory.color, 'coral')
assert.equal((await db.customFoodCategories.get(coralCategory.id))?.color, 'coral')
const sushiCategory = await createCustomCategory('sushi', 'amber')
assert.equal(sushiCategory.color, 'amber')
assert.equal((await db.customFoodCategories.get(sushiCategory.id))?.color, 'amber')
const customEntry = await addFoodLog(date, 'dinner', { name: 'Paneer Curry', categoryId: 'other', customCategoryId: custom.id, kcal: 410, protein: 22 })
assert.equal(customEntry.categoryKind, 'custom')
assert.equal(customEntry.customCategoryName, 'Homemade Curry')
assert.equal(customEntry.customCategoryColor, 'amber')
const violetCustom = await createCustomCategory('Evening Bowl', 'violet')
const violetEntry = await addFoodLog(date, 'supper', { name: 'Lentil Bowl', categoryId: 'other', customCategoryId: violetCustom.id, kcal: 280 })
assert.equal(violetEntry.customCategoryColor, 'violet')
assert.notEqual(violetEntry.customCategoryColor, customEntry.customCategoryColor)
await updateCustomCategory(custom.id, 'Family Curry', 'plum')
const stableSnapshot = await db.foodLogEntries.get(customEntry.id)
assert.equal(stableSnapshot?.customCategoryName, 'Homemade Curry')
assert.equal(stableSnapshot?.customCategoryColor, 'amber')
await addFoodLog(date, 'breakfast', { name: 'Poha', categoryId: 'other', customCategoryId: custom.id, kcal: 250, carbs: 40 })

const unusedCategory = await createCustomCategory('Unused category', 'slate')
await deleteCustomFoodCategory(unusedCategory.id)
assert.equal(await db.customFoodCategories.get(unusedCategory.id), undefined)
assert.ok(await db.rememberedFoods.where('normalizedName').equals('eggs').first(), 'Unrelated remembered food remains after deleting unused category')
assert.rejects(() => deleteCustomFoodCategory('chicken'), /Predefined food categories cannot be deleted/)

const preservedCustomEntry = await db.foodLogEntries.get(customEntry.id)
await deleteCustomFoodCategory(custom.id)
assert.equal(await db.customFoodCategories.get(custom.id), undefined)
assert.equal(await db.rememberedFoods.where('normalizedName').equals('paneer curry').count(), 0)
assert.equal(await db.rememberedFoods.where('normalizedName').equals('poha').count(), 0)
assert.equal((await searchRememberedFoods('paneer curry', 'dinner')).length, 0)
assert.equal((await searchRememberedFoods('poha', 'breakfast')).length, 0)
assert.ok(await db.rememberedFoods.where('normalizedName').equals('eggs').first(), 'Unrelated remembered food survives category deletion')
const orphanedEntry = await db.foodLogEntries.get(customEntry.id)
assert.equal(orphanedEntry?.id, customEntry.id)
assert.equal(orphanedEntry?.foodName, 'Paneer Curry')
assert.equal(orphanedEntry?.date, date)
assert.equal(orphanedEntry?.meal, 'dinner')
assert.equal(orphanedEntry?.kcal, preservedCustomEntry?.kcal)
assert.equal(orphanedEntry?.protein, preservedCustomEntry?.protein)
assert.equal(orphanedEntry?.categoryKind, 'unresolved')
assert.equal(orphanedEntry?.categoryId, undefined)
assert.equal(orphanedEntry?.categoryName, 'Uncategorized')
assert.equal(orphanedEntry?.customCategoryId, undefined)
assert.equal(orphanedEntry?.customCategoryName, undefined)
assert.equal(orphanedEntry?.customCategoryColor, 'amber')

const reassignedEntry = await editFoodLog(customEntry.id, { name: 'Paneer Curry', categoryId: 'chicken', kcal: 410, protein: 22 })
assert.equal(reassignedEntry.id, customEntry.id)
assert.equal(reassignedEntry.categoryId, 'chicken')
assert.equal(reassignedEntry.categoryName, 'Chicken')
assert.equal(reassignedEntry.categoryKind, 'predefined')
assert.equal(reassignedEntry.customCategoryId, undefined)
assert.equal(reassignedEntry.customCategoryColor, undefined)

const beforeEditMemory = await db.rememberedFoods.get(breakfast.rememberedFoodId!)
await editFoodLog(breakfast.id, { name: 'Chicken portion', categoryId: 'meat', kcal: 300, protein: 58, carbs: undefined })
const edited = await db.foodLogEntries.get(breakfast.id)
assert.equal(edited?.foodName, 'Chicken portion')
assert.equal(edited?.kcal, 300)
assert.equal(edited?.carbs, undefined)
assert.deepEqual(await db.rememberedFoods.get(breakfast.rememberedFoodId!), beforeEditMemory)
await deleteFoodLog(breakfast.id)
assert.equal(await db.foodLogEntries.get(breakfast.id), undefined)
assert.ok(await db.rememberedFoods.get(breakfast.rememberedFoodId!))

assert.equal(parseOptionalNutrition(''), undefined)
assert.equal(parseOptionalNutrition('0'), 0)
assert.equal(parseOptionalNutrition('1.25'), 1.25)
assert.throws(() => parseOptionalNutrition('-1'))
assert.throws(() => parseOptionalNutrition('not a number'))
assert.throws(() => validateNutrition({ kcal: Number.NaN }))
assert.throws(() => validateNutrition({ protein: Number.POSITIVE_INFINITY }))
assert.throws(() => validateNutrition({ fat: -0.1 }))
assert.equal(PREDEFINED_FOOD_CATEGORIES.length, 16)
assert.ok(PREDEFINED_FOOD_CATEGORIES.some((category) => category.id === 'flour-wheat' && category.name === 'Flour & Wheat'))
assert.ok(PREDEFINED_FOOD_CATEGORIES.some((category) => category.id === 'grains-rice'))
assert.ok(PREDEFINED_FOOD_CATEGORIES.some((category) => category.id === 'processed-foods'))
assert.ok(PREDEFINED_FOOD_CATEGORIES.some((category) => category.id === 'junk-food'))

const persistenceCategory = await createCustomCategory('Persistence orphan', 'coral')
const persistenceEntry = await addFoodLog(nextDate, 'lunch', { name: 'Persistent Curry', categoryId: 'other', customCategoryId: persistenceCategory.id, kcal: 450, protein: 32, carbs: 28, fat: 18 })
await deleteCustomFoodCategory(persistenceCategory.id)
const countBeforeReload = await db.foodLogEntries.count()
db.close()
await db.open()
assert.equal(await db.foodLogEntries.count(), countBeforeReload)
assert.equal((await db.customFoodCategories.get(coralCategory.id))?.color, 'coral')
assert.equal((await db.customFoodCategories.get(violetCustom.id))?.color, 'violet')
assert.equal((await db.customFoodCategories.get(sushiCategory.id))?.color, 'amber')
assert.equal(await db.customFoodCategories.get(custom.id), undefined)
assert.equal(await db.customFoodCategories.get(persistenceCategory.id), undefined)
assert.equal(await db.rememberedFoods.where('normalizedName').equals('persistent curry').count(), 0)
assert.equal((await db.foodLogEntries.get(persistenceEntry.id))?.categoryKind, 'unresolved')

db.close()
await Dexie.delete('fitdex')
console.log('Food repository tests passed: four meals/dates, totals, all nutrition values, validation, immutable snapshots, memory, normalization, suggestions, custom categories, edit/delete, and reopen persistence')
