/// <reference types="node" />
import assert from 'node:assert/strict'
import fs from 'node:fs'
import { customCategoryCssColor, resolveCustomCategoryColor } from './foodModel.ts'

const page = fs.readFileSync('src/pages/FoodPage.tsx', 'utf8')
const css = fs.readFileSync('src/styles/app.css', 'utf8')
const themeCss = fs.readFileSync('src/index.css', 'utf8')
const icons = fs.readFileSync('src/features/food/FoodIcons.tsx', 'utf8')
const model = fs.readFileSync('src/features/food/foodModel.ts', 'utf8')
const repository = fs.readFileSync('src/features/food/foodRepository.ts', 'utf8')
const pwa = fs.readFileSync('vite.config.ts', 'utf8')
const localDate = fs.readFileSync('src/utils/localDate.ts', 'utf8')

const breakfast = page.indexOf("'breakfast'")
assert.match(page, /FOOD_MEALS\.map/)
assert.match(model, /breakfast: 'Breakfast', lunch: 'Lunch', supper: 'Supper', dinner: 'Dinner'/)
assert.ok(breakfast === -1, 'Meal ordering must come from the locked FOOD_MEALS model, not duplicated UI literals')
assert.match(page, /Daily totals/i)
assert.match(page, /DailyTargetsCard/)
assert.match(page, /liveQuery\(loadNutritionTargets\)/)
assert.match(page, /targets\?\.enabled && targets\.calorieTarget > 0 \? <DailyTargetsCard/)
assert.match(page, /Daily targets/i)
assert.match(page, /aria-label=\{`\$\{label\}: \$\{Math\.round\(current\)\} of/)
assert.match(page, /target-status-dialog/)
assert.match(page, /onOpenSettings/)
assert.match(page, /evaluateCalorieDay/)
assert.match(page, /evaluateProteinDay/)
assert.match(page, /Nutrition breakdown/i)
assert.match(page, /How Food Works/)
assert.match(page, /hasSeenTutorial\('food'\)/)
assert.match(page, /aria-pressed=\{mode === 'macros'\}/)
assert.match(page, /aria-pressed=\{mode === 'meals'\}/)
assert.match(page, /className="food-donut"[\s\S]*role="img"/)
assert.match(page, /Macro split is calculated from logged protein, carbs, and fat/)
assert.match(model, /calculateMacroCalorieBreakdown/)
assert.match(model, /calculateMealCalorieBreakdown/)
assert.match(page, /Previous day/)
assert.match(page, /Next day/)
assert.match(page, /\{isLocalToday\(date\) \? <span className="food-today">Today<\/span> : null\}/)
assert.doesNotMatch(page, /date !== normalizeDate\(new Date\(\)\)/)
assert.match(localDate, /date\.getFullYear\(\)/)
assert.match(localDate, /date\.getMonth\(\) \+ 1/)
assert.match(localDate, /date\.getDate\(\)/)
assert.doesNotMatch(localDate, /toISOString/)
assert.match(page, /Recently eaten/)
assert.match(page, /Frequently eaten/)
assert.match(page, /Create new food/)
assert.match(page, /Core nutrition/)
assert.match(page, /More nutrition/)
assert.match(page, /Edit food/)
assert.match(page, /Delete \$\{entry\.foodName\}/)
assert.match(page, /Other \/ custom category/)
assert.match(page, /inputMode="decimal"/)
assert.match(page, /aria-modal="true"/)
assert.match(page, /Delete \$\{category\.name\} category/)
assert.match(page, /Food entries already logged in your history remain, but become Uncategorized/)
assert.match(page, /entry\.categoryKind === 'unresolved' \? 'Uncategorized'/)
assert.match(repository, /export async function deleteCustomFoodCategory/)
assert.match(repository, /db\.rememberedFoods\.bulkDelete/)
assert.match(repository, /entry\.categoryKind = 'unresolved'/)
assert.match(repository, /Predefined food categories cannot be deleted/)
assert.match(icons, /\/food\/meals\/meal-\$\{meal\}\.webp/)
assert.match(icons, /\/food\/categories\/category-\$\{categoryId\}\.webp/)
assert.match(icons, /CUSTOM_CATEGORY_ICON_ASSET_PATH = '\/food\/categories\/category-other\.webp'/)
assert.ok(fs.existsSync('public/food/categories/category-flour-wheat.webp'))
assert.ok(fs.existsSync('public/food/categories/category-other.webp'))
assert.equal(resolveCustomCategoryColor('amber'), 'amber')
assert.equal(resolveCustomCategoryColor('violet'), 'violet')
assert.equal(resolveCustomCategoryColor('invalid'), undefined)
assert.equal(resolveCustomCategoryColor(), undefined)
assert.equal(customCategoryCssColor('amber'), 'var(--food-custom-amber)')
assert.equal(customCategoryCssColor('violet'), 'var(--food-custom-violet)')
assert.equal(customCategoryCssColor('invalid'), 'var(--color-metal)')
assert.match(icons, /food-custom-sprite/)
assert.match(icons, /categoryId === 'other'/)
assert.match(icons, /predefinedCategoryIconAssetPath\(categoryId\)/)
assert.match(model, /flour-wheat/)
assert.match(model, /processed-foods/)
assert.match(model, /junk-food/)
assert.doesNotMatch(page, /🍳|🍗|🍚|🥗/u)
assert.match(css, /\.food-meal-list, \.food-entry-list, \.food-suggestions \{[^}]*display: grid;/s)
assert.match(css, /@media \(min-width: 700px\)[\s\S]*\.food-meal-list \{ grid-template-columns: repeat\(2,/)
assert.match(css, /var\(--color-primary\)/)
assert.match(css, /\.food-dialog \{[^}]*var\(--color-surface-raised\)/s)
assert.match(css, /\.food-meal-card \{[^}]*display: grid;/s)
assert.match(css, /\.food-breakdown-switch button \{[^}]*min-height: 44px/s)
assert.match(css, /\.daily-targets \{ display: grid; gap: 14px; \}/)
assert.match(css, /\.daily-target-metric \{[^}]*min-width: 0;[^}]*background: var\(--color-surface-subtle\)/s)
assert.match(css, /@media \(max-width: 599px\)[\s\S]*\.food-breakdown-body \{ grid-template-columns: 1fr; \}/)
assert.match(page, /<label className="food-search">[\s\S]*placeholder="Search foods you've logged"[\s\S]*aria-label="Clear search"[\s\S]*onClick=\{\(\) => setQuery\(''\)\}/)
assert.match(css, /\.food-search \{[^}]*display: flex;[^}]*min-height: 48px;[^}]*border: 2px solid var\(--color-border\);/s)
assert.match(css, /\.food-search:focus-within \{ border-color: var\(--color-focus\); outline: 0; \}/)
assert.match(css, /\.food-search input \{[^}]*flex: 1 1 auto;[^}]*min-width: 0;[^}]*border: 0;[^}]*outline: 0;[^}]*box-shadow: none;/s)
assert.match(css, /\.food-search input:focus-visible \{ outline: 0; \}/)
assert.match(css, /\.food-search button:focus-visible \{ outline: 2px solid var\(--color-focus\);/)
assert.match(css, /\.food-search button \{[^}]*border: 0;[^}]*box-shadow: none;[^}]*background: transparent;/s)
assert.doesNotMatch(css, /\.food-search \{[^}]*grid-template-columns:/s)
assert.match(css, /\.food-custom-mask \{[^}]*-webkit-mask-image: var\(--food-custom-icon\);[^}]*mask-image: var\(--food-custom-icon\);/s)
assert.match(css, /-webkit-mask-repeat: no-repeat;\s*mask-repeat: no-repeat;/)
assert.match(css, /-webkit-mask-position: center;\s*mask-position: center;/)
assert.match(css, /-webkit-mask-size: contain;\s*mask-size: contain;/)
assert.doesNotMatch(icons, /category-other-(?:red|blue|green)\.webp/)
assert.match(page, /aria-label=\{`Icon accent color: \$\{item\}`\}/)
assert.match(page, /<CustomFoodCategoryIcon label=\{name\.trim\(\) \|\| 'Custom category'\} color=\{color\} \/>/)
assert.match(page, /<FoodCategoryIcon categoryId="other" label=\{category\.name\} color=\{category\.color\} \/>/)
assert.match(page, /const \[customCategoryColor, setCustomCategoryColor\] = useState\(initial\?\.customCategoryColor\)/)
assert.match(page, /<FoodCategoryIcon categoryId=\{categoryId\} label=\{customCategoryLabel \?\? categoryName\(categoryId\)\} color=\{customCategoryColor\} \/>/)
assert.match(page, /onSelect\('other', category\.id, category\.name, category\.color\)/)
assert.match(page, /'--food-category-color': customCategoryCssColor\(item\)/)
assert.match(page, /onChange=\{\(\) => setColor\(item\)\}/)
assert.match(page, /Live icon preview/)
assert.match(css, /\.color-picker span \{[^}]*background: var\(--food-category-color\)/s)
assert.match(css, /\.color-picker label:has\(input:checked\)::after/)
assert.doesNotMatch(css.match(/\.color-picker span \{[^}]*\}/s)?.[0] ?? '', /currentColor|color: transparent/)

const customColorValues = {
  amber: '#a86b08', coral: '#b85c43', crimson: '#a93d52', plum: '#805080', violet: '#6958a8',
  blue: '#326da8', teal: '#247b78', green: '#487d49', olive: '#74733a', slate: '#596773',
}
assert.equal(Object.keys(customColorValues).length, 10)
assert.equal(new Set(Object.values(customColorValues)).size, 10)
for (const [token, value] of Object.entries(customColorValues)) {
  assert.match(themeCss, new RegExp(`--food-custom-${token}: ${value};`))
  assert.equal(customCategoryCssColor(token), `var(--food-custom-${token})`)
}
assert.match(themeCss, /:root\[data-theme-family='amazonians'\]/)
assert.match(themeCss, /:root\[data-theme-family='spartans'\]\[data-brightness='dark'\]/)
assert.match(themeCss, /:root\[data-theme-family='amazonians'\]\[data-brightness='dark'\]/)
assert.match(icons, /export function CustomFoodCategoryIcon/)
assert.match(icons, /customCategoryMaskStyle\(color\)/)
assert.match(icons, /'--food-category-color': customCategoryCssColor\(color\)/)
assert.match(icons, /if \(categoryId === 'other'\) return <CustomFoodCategoryIcon label=\{label\} color=\{color\} \/>/)
assert.doesNotMatch(icons, /Salad/)
assert.doesNotMatch(icons, /<img[^>]*category-other/)
assert.match(pwa, /globPatterns: \['\*\*\/\*\.\{js,css,html,svg,png,woff2\}'\]/)
assert.doesNotMatch(pwa, /webp/)

console.log('Food UI assertions passed: overview, locked meals, date navigation, suggestions/details, categories, edit/delete, responsive layout, accessibility, and replaceable sprite slots')
