/// <reference types="node" />
import 'fake-indexeddb/auto'
import assert from 'node:assert/strict'
import Dexie from 'dexie'
import fs from 'node:fs'
import type { PlanDaySnapshot } from '../../data/models.ts'
import { ACHIEVEMENTS } from './achievementCatalog.ts'
import { ACHIEVEMENT_BADGE_ASSET_FILES, LEVEL_XP_THRESHOLDS, MAX_LEVEL, RANK_BADGE_ASSET_FILES, RANKS, XP_REWARDS, achievementAssetPath, levelForXp, rankAssetPath, rankForLevel } from './gamificationConfig.ts'
import { deriveStreak, inclusiveDateDuration, isMaterialPlanChange } from './gamificationModel.ts'

assert.equal(ACHIEVEMENTS.length, 52)
assert.deepEqual(ACHIEVEMENTS.filter((item) => item.category === 'EXERCISE_DEX').map((item) => item.name), ['First Exercise', '5 Different Exercises', '10 Different Exercises', '25 Different Exercises', '50 Different Exercises', 'All Categories'])
assert.deepEqual(Object.fromEntries(['WORKOUT', 'CONSISTENCY', 'PERFORMANCE', 'EXERCISE_DEX', 'NUTRITION', 'PROGRESSION'].map((category) => [category, ACHIEVEMENTS.filter((item) => item.category === category).length])), { WORKOUT: 10, CONSISTENCY: 8, PERFORMANCE: 7, EXERCISE_DEX: 6, NUTRITION: 11, PROGRESSION: 10 })
assert.deepEqual(XP_REWARDS, { plannedRoutine: 30, plannedWorkout: 30, unplannedWorkout: 20, personalRecord: 15, calorieTarget: 5, proteinTarget: 5, fullFoodLog: 5 })
assert.ok(ACHIEVEMENTS.filter((achievement) => achievement.id.startsWith('calorie-target-') || achievement.id.startsWith('protein-target-')).every((achievement) => !achievement.dormant))
assert.ok(!Object.keys(XP_REWARDS).some((reward) => /(?:carb|fat|fiber)/i.test(reward)))
assert.ok(!ACHIEVEMENTS.some((achievement) => /(?:carb|fat|fiber)-target/i.test(achievement.id)))

assert.equal(LEVEL_XP_THRESHOLDS.length, 100)
assert.equal(LEVEL_XP_THRESHOLDS[0], 0)
for (let index = 1; index < LEVEL_XP_THRESHOLDS.length; index += 1) assert.ok(LEVEL_XP_THRESHOLDS[index] > LEVEL_XP_THRESHOLDS[index - 1])
assert.ok(LEVEL_XP_THRESHOLDS[9] >= 1800 && LEVEL_XP_THRESHOLDS[9] <= 2200)
assert.ok(LEVEL_XP_THRESHOLDS[24] >= 11000 && LEVEL_XP_THRESHOLDS[24] <= 13000)
assert.ok(LEVEL_XP_THRESHOLDS[49] >= 24000 && LEVEL_XP_THRESHOLDS[49] <= 30000)
assert.ok(LEVEL_XP_THRESHOLDS[74] >= 60000 && LEVEL_XP_THRESHOLDS[74] <= 80000)
assert.ok(LEVEL_XP_THRESHOLDS[99] >= 125000 && LEVEL_XP_THRESHOLDS[99] <= 150000)
assert.equal(levelForXp(Number.MAX_SAFE_INTEGER).level, MAX_LEVEL)
assert.equal(levelForXp(Number.MAX_SAFE_INTEGER).maxLevel, true)

const boundaries = [[1, 'RECRUIT'], [6, 'RECRUIT'], [7, 'REGULAR'], [15, 'REGULAR'], [16, 'HARDENED'], [27, 'HARDENED'], [28, 'VETERAN'], [42, 'VETERAN'], [43, 'WARRIOR'], [57, 'WARRIOR'], [58, 'ASCENDANT'], [72, 'ASCENDANT'], [73, 'IMMORTAL'], [87, 'IMMORTAL'], [88, 'LEGEND'], [99, 'LEGEND'], [100, 'RADIANT']] as const
for (const [level, rank] of boundaries) assert.equal(rankForLevel(level).name, rank)
assert.equal(RANKS.length, 9)
assert.ok(RANKS.every((rank) => !/[IVX]+$/.test(rank.name)))
assert.equal(rankAssetPath('radiant'), '/gamification/ranks/radiant.webp')
assert.equal(rankAssetPath('veteran'), '/gamification/ranks/veteran.webp')
assert.equal(rankAssetPath('immortal'), '/gamification/ranks/immortal.webp')
assert.equal(rankAssetPath('unknown-rank'), '/gamification/ranks/unknown-rank.webp')
assert.equal(achievementAssetPath('first-workout'), '/gamification/achievements/first-workout.webp')
assert.equal(achievementAssetPath('first-fully-logged-day'), '/gamification/achievements/first-full-log.webp')
assert.equal(achievementAssetPath('first-pr'), '/gamification/achievements/first-pr.webp')
assert.equal(achievementAssetPath('reach-veteran'), '/gamification/achievements/reach-veteran.webp')
assert.equal(achievementAssetPath('10-workouts'), '/gamification/achievements/workouts-10.webp')
assert.equal(achievementAssetPath('100-hours-trained'), '/gamification/achievements/hours-100.webp')
assert.equal(achievementAssetPath('7-day-plan-streak'), '/gamification/achievements/streak-7.webp')
assert.equal(achievementAssetPath('level-10'), '/gamification/achievements/level-10.webp')
assert.equal(achievementAssetPath('level-100'), '/gamification/achievements/level-100.webp')
assert.equal(achievementAssetPath('first-fully-logged-day'), '/gamification/achievements/first-full-log.webp')
assert.equal(achievementAssetPath('not-yet-known'), '/gamification/achievements/not-yet-known.webp')
assert.deepEqual(Object.keys(RANK_BADGE_ASSET_FILES).sort(), RANKS.map((rank) => rank.id).sort())
assert.deepEqual(Object.keys(ACHIEVEMENT_BADGE_ASSET_FILES).sort(), ACHIEVEMENTS.map((achievement) => achievement.id).sort())
assert.equal(Object.keys(RANK_BADGE_ASSET_FILES).length, 9)
assert.equal(Object.keys(ACHIEVEMENT_BADGE_ASSET_FILES).length, 52)
assert.equal(new Set(Object.values(ACHIEVEMENT_BADGE_ASSET_FILES)).size, 52)
assert.deepEqual(fs.readdirSync('public/gamification/ranks').sort(), Object.values(RANK_BADGE_ASSET_FILES).sort())
assert.deepEqual(fs.readdirSync('public/gamification/achievements').sort(), Object.values(ACHIEVEMENT_BADGE_ASSET_FILES).sort())
for (const [rankId, fileName] of Object.entries(RANK_BADGE_ASSET_FILES)) {
  const assetPath = rankAssetPath(rankId)
  assert.equal(assetPath, `/gamification/ranks/${fileName}`)
  assert.ok(fs.existsSync(`public${assetPath}`), `missing rank asset: ${assetPath}`)
  const bytes = fs.readFileSync(`public${assetPath}`)
  assert.equal(bytes.subarray(0, 4).toString('ascii'), 'RIFF', `invalid WebP RIFF header: ${assetPath}`)
  assert.equal(bytes.subarray(8, 12).toString('ascii'), 'WEBP', `invalid WebP header: ${assetPath}`)
}
for (const achievement of ACHIEVEMENTS) {
  const assetPath = achievementAssetPath(achievement.id)
  assert.equal(assetPath, `/gamification/achievements/${ACHIEVEMENT_BADGE_ASSET_FILES[achievement.id]}`)
  assert.ok(fs.existsSync(`public${assetPath}`), `missing achievement asset: ${assetPath}`)
  const bytes = fs.readFileSync(`public${assetPath}`)
  assert.equal(bytes.subarray(0, 4).toString('ascii'), 'RIFF', `invalid WebP RIFF header: ${assetPath}`)
  assert.equal(bytes.subarray(8, 12).toString('ascii'), 'WEBP', `invalid WebP header: ${assetPath}`)
}
const badgeSource = fs.readFileSync('src/features/gamification/GamificationBadge.tsx', 'utf8')
assert.match(badgeSource, /onError=\{\(\) => setFailed\(true\)\}/)
assert.match(badgeSource, /kind === 'rank' \? <Shield/)
assert.match(badgeSource, /is-locked/)
assert.match(badgeSource, /alt=\{accessibleLabel\}/)
const notificationSource = fs.readFileSync('src/features/gamification/GamificationViews.tsx', 'utf8')
assert.match(notificationSource, /achievementAssetPath\(achievement\.id\)/)
assert.match(notificationSource, /achievementAssetPath\(unlock\.achievementId\)/)
assert.match(notificationSource, /rankAssetPath\(pending\.afterProgress\.rank\)/)
assert.match(notificationSource, /LEVEL_MILESTONE_ACHIEVEMENT_IDS/)
assert.doesNotMatch(notificationSource, /Trophy/)
assert.match(notificationSource, /markGamificationNotificationsSeen\(\)/)
const gamificationRepositorySource = fs.readFileSync('src/features/gamification/gamificationRepository.ts', 'utf8')
assert.match(gamificationRepositorySource, /evaluateCalorieDay\(targets, calories, estimatedTdee\)\.achievementEligible/)
assert.match(gamificationRepositorySource, /evaluateProteinDay\(targets\.proteinTargetGrams, protein\)\.achievementEligible/)
assert.match(gamificationRepositorySource, /calorie-target:\$\{date\}/)
assert.match(gamificationRepositorySource, /protein-target:\$\{date\}/)

const row = (localDate: string, plannedType: PlanDaySnapshot['plannedType'], result: PlanDaySnapshot['result']): PlanDaySnapshot => ({ id: localDate, localDate, plannedType, result, createdAt: localDate, updatedAt: localDate })
assert.deepEqual(deriveStreak([row('2026-01-01', 'routine', 'success'), row('2026-01-02', 'rest_day', 'rest'), row('2026-01-03', 'no_plan', 'no_plan'), row('2026-01-04', 'workout_day', 'frozen'), row('2026-01-05', 'routine', 'paused'), row('2026-01-06', 'routine', 'success')]), { current: 2, best: 2, successfulPlannedDays: 2 })
assert.equal(deriveStreak([row('2026-01-01', 'routine', 'success'), row('2026-01-02', 'routine', 'missed')]).current, 0)
assert.equal(deriveStreak([row('2026-01-01', 'routine', 'success'), row('2026-01-02', 'routine', 'success')], [{ id: 'reset', sourceKey: 'reset', type: 'reset', effectiveDate: '2026-01-02', occurredAt: '2026-01-02T00:00:00', createdAt: '', updatedAt: '' }]).current, 1)
assert.equal(inclusiveDateDuration('2026-08-01', '2026-08-07'), 7)
assert.equal(inclusiveDateDuration('2026-08-01', '2026-08-08'), 8)
assert.equal(isMaterialPlanChange({ type: 'routine', routineId: 'a' }, { type: 'routine', routineId: 'a' }), false)
assert.equal(isMaterialPlanChange({ type: 'routine', routineId: 'a' }, { type: 'routine', routineId: 'b' }), true)

await Dexie.delete('fitdex')
const { db } = await import('../../data/database.ts')
const { loadGamificationDashboard, planStreakPause, reconcileGamification } = await import('./gamificationRepository.ts')
const yesterday = '2026-08-25'
const today = '2026-08-26'
await db.settings.put({ id: 'settings', weeklyPlanConfigured: true, weeklyPlan: { tuesday: { type: 'workout_day' } }, gamificationInitializedAt: '2026-08-25T00:00:00.000Z', createdAt: '2026-08-25T00:00:00.000Z', updatedAt: '2026-08-25T00:00:00.000Z' })
await db.workouts.put({ id: 'workout:planned', nameSnapshot: 'Workout A', status: 'completed', startedAt: `${yesterday}T10:00:00.000Z`, completedAt: `${yesterday}T11:00:00.000Z`, durationSeconds: 3600, createdAt: `${yesterday}T10:00:00.000Z`, updatedAt: `${yesterday}T11:00:00.000Z` })
await reconcileGamification(new Date(`${today}T12:00:00`))
await reconcileGamification(new Date(`${today}T12:00:00`))
assert.equal(await db.xpEvents.where('sourceKey').equals('workout:workout:planned').count(), 1)
assert.equal((await db.xpEvents.where('sourceKey').equals('workout:workout:planned').first())?.amount, 30)
assert.equal((await db.planDaySnapshots.get(`plan-day:${yesterday}`))?.result, 'success')
assert.equal(await db.streakFreezeEvents.where('type').equals('automatic_missed_plan').count(), 0)
assert.equal((await db.planDaySnapshots.get(`plan-day:${today}`))?.result, 'pending')

await db.exercises.put({ id: 'exercise:pr', name: 'PR Exercise', aliases: [], category: 'Chest', categories: ['Chest'], primaryCategory: 'Chest', primaryMuscles: ['Chest'], secondaryMuscles: [], muscleRegions: ['Chest'], equipment: 'Bodyweight', trackingType: 'reps_only', movementPattern: 'Horizontal Push', source: 'custom', archived: false, createdAt: `${yesterday}T00:00:00.000Z`, updatedAt: `${yesterday}T00:00:00.000Z` })
await db.workouts.put({ id: 'workout:extra', nameSnapshot: 'Extra Workout', status: 'completed', startedAt: `${yesterday}T12:00:00.000Z`, completedAt: `${yesterday}T13:00:00.000Z`, durationSeconds: 3600, createdAt: `${yesterday}T12:00:00.000Z`, updatedAt: `${yesterday}T13:00:00.000Z` })
await db.workoutExercises.put({ id: 'workout-exercise:pr', workoutId: 'workout:extra', exerciseId: 'exercise:pr', exerciseNameSnapshot: 'PR Exercise', exerciseCategorySnapshot: 'Chest', trackingTypeSnapshot: 'reps_only', order: 0, createdAt: `${yesterday}T12:00:00.000Z`, updatedAt: `${yesterday}T13:00:00.000Z` })
await db.workoutSets.put({ id: 'workout-set:pr', workoutExerciseId: 'workout-exercise:pr', order: 0, reps: 10, completed: true, createdAt: `${yesterday}T12:00:00.000Z`, updatedAt: `${yesterday}T13:00:00.000Z` })
await reconcileGamification(new Date(`${today}T12:00:00`))
await reconcileGamification(new Date(`${today}T12:00:00`))
assert.equal((await db.xpEvents.get('workout:workout:extra'))?.amount, 20, 'an additional workout is unplanned rather than duplicate planned XP')
assert.equal(await db.xpEvents.where('type').equals('personal_record').count(), 1)
assert.equal((await db.xpEvents.where('type').equals('personal_record').first())?.amount, 15)

await db.planDaySnapshots.update(`plan-day:${today}`, { plannedType: 'workout_day', result: 'pending' })
await reconcileGamification(new Date('2026-08-27T12:00:00'))
await reconcileGamification(new Date('2026-08-27T12:00:00'))
assert.equal((await db.planDaySnapshots.get('plan-day:2026-08-26'))?.result, 'frozen')
assert.equal(await db.streakFreezeEvents.where('sourceKey').equals('freeze:missed:2026-08-26').count(), 1)
assert.equal((await loadGamificationDashboard('2026-08-27', false)).freezeBalance, 1)

await db.planDaySnapshots.update('plan-day:2026-08-27', { plannedType: 'routine', routineId: 'routine:missing', result: 'pending' })
await reconcileGamification(new Date('2026-08-28T12:00:00'))
assert.equal((await db.planDaySnapshots.get('plan-day:2026-08-27'))?.result, 'frozen')
assert.equal((await loadGamificationDashboard('2026-08-28', false)).freezeBalance, 0)

await db.planDaySnapshots.update('plan-day:2026-08-28', { plannedType: 'workout_day', result: 'pending' })
await reconcileGamification(new Date('2026-08-29T12:00:00'))
assert.equal((await db.planDaySnapshots.get('plan-day:2026-08-28'))?.result, 'missed')
assert.equal((await loadGamificationDashboard('2026-08-29', false)).streak.current, 0)

await assert.rejects(() => planStreakPause('travel', '2026-08-29', '2026-09-05', '2026-08-29'), /between 1 and 7/)
await planStreakPause('travel', '2026-08-29', '2026-08-30', '2026-08-29')
await db.planDaySnapshots.update('plan-day:2026-08-29', { plannedType: 'workout_day', result: 'pending' })
await reconcileGamification(new Date('2026-08-31T12:00:00'))
assert.equal((await db.planDaySnapshots.get('plan-day:2026-08-29'))?.result, 'paused')
assert.equal((await db.planDaySnapshots.get('plan-day:2026-08-30'))?.result, 'paused')
assert.equal((await loadGamificationDashboard('2026-08-31', false)).freezeBalance, 0)
await planStreakPause('sickness', '2026-09-01', '2026-09-01', '2026-08-31')
await assert.rejects(() => planStreakPause('travel', '2026-09-02', '2026-09-02', '2026-08-31'), /Both Travel \/ Sickness Pauses/)
await db.close()
await Dexie.delete('fitdex')

console.log('Gamification tests passed: 52 achievements, progression/rank boundaries, streak semantics, automatic Freeze/no-Freeze outcomes, Pause limits, plan-change identity, and repeat-safe planned XP reconciliation')
