import { ArrowLeft, Award, ChevronRight, CircleHelp, Search, Utensils } from 'lucide-react'
import { type CSSProperties, useEffect, useMemo, useState } from 'react'
import { Panel } from '../components/ui/Panel'
import { PageFrame } from '../components/layout/PageFrame'
import { derivePersonalRecords, formatPersonalRecordDate, formatPersonalRecordMetric, searchPersonalRecords, type ExercisePersonalRecords } from '../features/progress/personalRecords'
import { buildNutritionTrend, buildVolumeTrend, buildWorkoutFrequencyTrend, calculateNutritionSummary, calculateTrainingSeconds, calculateTrainingVolume, calculateVolumeComparison, formatTrainingTime, PROGRESS_PERIODS, type ProgressPeriod, type TrendBucket } from '../features/progress/progressModel'
import { loadProgressSource, type ProgressSourceData } from '../features/progress/progressRepository'
import { getLocalDateKey } from '../utils/localDate'
import { displayWeightFromKg } from '../utils/units'
import { PageHeader } from './PageHeader'
import { GuideDialog, type GuideStep } from '../features/help/GuideDialog'
import { AchievementsView, RankDetailView } from '../features/gamification/GamificationViews'
import { GamificationBadge } from '../features/gamification/GamificationBadge'
import { rankAssetPath } from '../features/gamification/gamificationConfig'
import { loadGamificationDashboard, type GamificationDashboard } from '../features/gamification/gamificationRepository'
import { useAudio } from '../features/audio/useAudio'
import { useBackNavigation } from '../features/navigation/useBackNavigation'

const PERIOD_LABELS: Record<ProgressPeriod, string> = { '7d': '7D', '30d': '30D', '90d': '90D', all: 'All' }
const progressHelpSteps: readonly GuideStep[] = [{ title: 'How Progress Works', sections: [{ text: 'Progress is calculated automatically from completed workouts and Food history. There is nothing extra to log here.' }, { label: 'Workout data', bullets: ['Workout count', 'Training time', 'Resistance Volume', 'Personal Records'] }, { label: 'Food data', bullets: ['Average calories', 'Average protein', 'Nutrition trends'] }, { label: 'Resistance Volume', text: 'Weight × reps across logged weight-based resistance sets. It is a workload measure, not a universal score of training quality.' }] }]
type TrendMode = 'workouts' | 'volume' | 'nutrition'

export function ProgressPage({ initialView = 'overview' }: { initialView?: 'overview' | 'achievements' }) {
  const { playEffect } = useAudio()
  const [period, setPeriod] = useState<ProgressPeriod>('30d')
  const [trend, setTrend] = useState<TrendMode>('volume')
  const [data, setData] = useState<ProgressSourceData>()
  const [error, setError] = useState('')
  const [recordsOpen, setRecordsOpen] = useState(false)
  const [helpOpen, setHelpOpen] = useState(false)
  const [view, setView] = useState<'overview' | 'records' | 'achievements' | 'rank'>(initialView)
  const [gamification, setGamification] = useState<GamificationDashboard>()
  const referenceDateKey = getLocalDateKey()
  const navigateBack = useBackNavigation('progress-subview', recordsOpen || view !== 'overview', () => { setRecordsOpen(false); setView('overview') })
  useEffect(() => {
    let current = true
    void loadProgressSource(period, referenceDateKey).then((result) => { if (current) setData(result) }).catch((reason: unknown) => { if (current) setError(reason instanceof Error ? reason.message : 'Progress history could not be loaded.') })
    return () => { current = false }
  }, [period, referenceDateKey])
  useEffect(() => {
    let current = true
    const refreshGamification = (reconcile: boolean) => { void loadGamificationDashboard(referenceDateKey, reconcile).then((result) => { if (current) setGamification(result) }) }
    const handleGamificationChanged = () => refreshGamification(false)
    window.addEventListener('fitdex:gamification-changed', handleGamificationChanged)
    refreshGamification(true)
    return () => { current = false; window.removeEventListener('fitdex:gamification-changed', handleGamificationChanged) }
  }, [referenceDateKey])
  const records = useMemo(() => data ? derivePersonalRecords(data.allWorkouts, data.definitions) : [], [data])
  if ((recordsOpen || view === 'records') && data) return <PersonalRecordsView records={records} units={data.units} onBack={() => { void navigateBack() }} />
  if (view === 'achievements' && gamification) return <AchievementsView data={gamification} onBack={() => setView('overview')} />
  if (view === 'rank' && gamification) return <RankDetailView data={gamification} onBack={() => setView('overview')} />
  const selectPeriod = (next: ProgressPeriod) => { playEffect('select'); setData(undefined); setError(''); setPeriod(next) }
  const workoutCount = data?.currentWorkouts.length ?? 0
  const trainingSeconds = calculateTrainingSeconds(data?.currentWorkouts ?? [])
  const volumeKg = calculateTrainingVolume(data?.currentWorkouts ?? [])
  const previousVolumeKg = calculateTrainingVolume(data?.previousWorkouts ?? [])
  const comparison = calculateVolumeComparison(volumeKg, previousVolumeKg, period)
  const nutrition = calculateNutritionSummary(data?.foodEntries ?? [])
  const displayVolume = data ? displayWeightFromKg(volumeKg, data.units.preference) : 0
  const trends = { workouts: buildWorkoutFrequencyTrend(data?.currentWorkouts ?? [], period, referenceDateKey), volume: buildVolumeTrend(data?.currentWorkouts ?? [], period, referenceDateKey).map((bucket) => ({ ...bucket, value: data ? displayWeightFromKg(bucket.value, data.units.preference) : 0 })), nutrition: buildNutritionTrend(data?.foodEntries ?? [], period, referenceDateKey) }
  const trendMeta = trend === 'workouts' ? { title: workoutCount ? `${workoutCount} completed ${workoutCount === 1 ? 'workout' : 'workouts'}` : 'No completed training in this period', valueLabel: 'workouts', emptyText: 'No completed workouts in this period.', summary: 'Completed training sessions in this period.' } : trend === 'volume' ? { title: `${formatNumber(displayVolume)} ${data?.units.weightLabel ?? 'kg'} resistance volume`, valueLabel: data?.units.weightLabel ?? 'kg', emptyText: 'No completed weight-and-reps volume in this period.', summary: 'Total weight × reps across logged resistance sets.' } : { title: nutrition.loggedDays ? `${formatNumber(nutrition.averageKcal)} kcal average` : 'No food history in this period', valueLabel: 'average kcal', emptyText: 'Logged foods have no calorie values in this period.', summary: 'Averages use days with at least one food entry.' }
  return <PageFrame className="page-stack progress-page">
    <PageHeader eyebrow="Character stats" title="Progress" description="See how your training is changing" action={<button className="page-help-button progress-help-button" type="button" onClick={() => { playEffect('select'); setHelpOpen(true) }} aria-label="How Progress Works"><CircleHelp size={18} aria-hidden="true" /><span>How Progress Works</span></button>} />
    <nav className="progress-view-tabs" role="tablist" aria-label="Progress sections"><button type="button" role="tab" aria-selected={view === 'overview'} onClick={() => { playEffect('select'); setView('overview') }}>Overview</button><button type="button" role="tab" aria-selected="false" onClick={() => { playEffect('select'); setView('records') }}>Records</button><button type="button" role="tab" aria-selected="false" onClick={() => { playEffect('select'); setView('achievements') }}>Achievements</button></nav>
    {gamification ? <CharacterHero data={gamification} onRank={() => { playEffect('select'); setView('rank') }} onAchievements={() => { playEffect('select'); setView('achievements') }} /> : null}
    <section className="progress-period" aria-labelledby="progress-period-title"><p className="eyebrow" id="progress-period-title">Period</p><div>{PROGRESS_PERIODS.map((item) => <button type="button" key={item} aria-pressed={period === item} className={period === item ? 'is-selected' : ''} onClick={() => selectPeriod(item)}>{PERIOD_LABELS[item]}</button>)}</div></section>
    {!data ? <Panel className="progress-state"><p className="progress-loading" aria-live="polite">{error ? 'Progress unavailable' : 'Loading progress…'}</p>{error ? <p className="form-error" role="alert">{error}</p> : null}</Panel> : !data.hasAnyHistory ? <Panel className="progress-empty"><span className="empty-glyph" aria-hidden="true">↗</span><div><h2>Start building your history</h2><p>Complete workouts and log meals to see progress here.</p></div></Panel> : <>
      <Panel className="progress-section progress-attributes" eyebrow="Training attributes" title="Real progress stats"><div className="progress-attribute-list"><Attribute number="01" label="Consistency" detail="Completed workouts" value={formatNumber(workoutCount)} /><Attribute number="02" label="Training Time" detail="Completed session duration" value={formatTrainingTime(trainingSeconds)} /><Attribute number="03" label="Resistance Volume" detail={comparison.kind === 'percent' ? `${comparison.percent >= 0 ? '+' : ''}${formatNumber(comparison.percent)}% vs previous period` : comparison.kind === 'no-previous' ? 'No previous volume' : 'All-time total'} value={`${formatNumber(displayVolume)} ${data.units.weightLabel}`} /><Attribute number="04" label="Record Book" detail="Exercises with records" value={formatNumber(records.length)} /></div></Panel>
      <Panel className="progress-section progress-evidence" eyebrow="Logged evidence" title={trendMeta.title}><div className="progress-trend-switch" role="group" aria-label="Progress trend">{(['workouts', 'volume', 'nutrition'] as const).map((item) => <button type="button" key={item} aria-pressed={trend === item} onClick={() => { playEffect('select'); setTrend(item) }}>{item}</button>)}</div><SimpleBarChart buckets={trends[trend]} valueLabel={trendMeta.valueLabel} emptyText={trendMeta.emptyText} /><p className="progress-chart-summary">{trendMeta.summary}</p>{trend === 'volume' && comparison.kind === 'percent' ? <p className="progress-comparison">{comparison.percent >= 0 ? '+' : ''}{formatNumber(comparison.percent)}% vs previous period</p> : trend === 'volume' && comparison.kind === 'no-previous' ? <p className="progress-comparison">No previous volume</p> : null}</Panel>
      <Panel className="progress-section progress-pr-preview" eyebrow="Personal records" title={records.length ? `${records.length} exercises with records` : 'No valid records yet'}>{records.length ? <div className="progress-pr-list">{records.slice(0, 3).map((record) => <PrPreview key={record.exerciseId} record={record} units={data.units} />)}</div> : <p className="progress-no-data">Complete measurable sets to establish personal records.</p>}<button className="progress-pr-cta" type="button" onClick={() => { playEffect('select'); setRecordsOpen(true); setView('records') }}><span><Award size={20} aria-hidden="true" /> View All PRs</span><ChevronRight size={18} aria-hidden="true" /></button></Panel>
      <Panel className="progress-section" eyebrow="Nutrition" title={nutrition.loggedDays ? `${nutrition.loggedDays} logged ${nutrition.loggedDays === 1 ? 'day' : 'days'}` : 'No food history in this period'}>{nutrition.loggedDays ? <div className="nutrition-average-grid"><span><strong>{formatNumber(nutrition.averageKcal)} kcal</strong><small>Average Calories</small></span><span><strong>{formatNumber(nutrition.averageProtein)} g</strong><small>Average Protein</small></span></div> : <div className="progress-no-data"><Utensils aria-hidden="true" /><p>Log meals in Food to see calorie and protein history.</p></div>}</Panel>
    </>}
    {helpOpen ? <GuideDialog eyebrow="Connected insights" steps={progressHelpSteps} onClose={() => setHelpOpen(false)} /> : null}
  </PageFrame>
}
function CharacterHero({ data, onRank, onAchievements }: { data: GamificationDashboard; onRank: () => void; onAchievements: () => void }) { const { progression } = data; const percent = progression.maxLevel ? 100 : Math.min(100, (progression.xpIntoLevel / progression.xpRequiredForNextLevel) * 100); return <Panel className="progress-character-hero"><GamificationBadge kind="rank" src={rankAssetPath(progression.rank)} label={`${progression.rank.name} rank emblem`} /><div className="progress-character-copy"><p className="eyebrow">Level {progression.level}</p><h2>{progression.rank.name}</h2><p>{progression.totalXp.toLocaleString()} Lifetime XP</p><div className="gamification-progress" role="progressbar" aria-label={progression.maxLevel ? 'Maximum level reached' : `Level ${progression.level} XP progress`} aria-valuemin={0} aria-valuemax={progression.maxLevel ? 100 : progression.xpRequiredForNextLevel} aria-valuenow={progression.maxLevel ? 100 : progression.xpIntoLevel}><i style={{ width: `${percent}%` }} /></div><small>{progression.maxLevel ? 'MAX LEVEL' : `${progression.xpIntoLevel.toLocaleString()} / ${progression.xpRequiredForNextLevel.toLocaleString()} XP to Level ${progression.level + 1}`}</small></div><div className="progress-character-actions"><button className="secondary-button" type="button" onClick={onRank}>Rank Journey</button><button className="secondary-button" type="button" onClick={onAchievements}>Achievements</button></div></Panel> }
function Attribute({ number, label, detail, value }: { number: string; label: string; detail: string; value: string }) { return <div className="progress-attribute"><b>{number}</b><span><strong>{label}</strong><small>{detail}</small></span><em>{value}</em></div> }
function SimpleBarChart({ buckets, valueLabel, emptyText }: { buckets: TrendBucket[]; valueLabel: string; emptyText: string }) { const maximum = Math.max(0, ...buckets.map((bucket) => bucket.value)); if (!buckets.length || maximum === 0) return <p className="progress-chart-empty">{emptyText}</p>; return <div className="progress-chart" role="img" aria-label={buckets.map((bucket) => `${bucket.label}: ${formatNumber(bucket.value)} ${valueLabel}`).join('; ')}>{buckets.map((bucket) => <div className="progress-chart-column" key={bucket.key} aria-hidden="true"><span className="progress-chart-value">{formatCompact(bucket.value)}</span><i style={{ '--progress-bar-height': `${Math.max(4, (bucket.value / maximum) * 100)}%` } as CSSProperties} /><small>{bucket.label}</small></div>)}</div> }
function PrPreview({ record, units }: { record: ExercisePersonalRecords; units: ProgressSourceData['units'] }) { const metric = record.metrics[0]; return <article><div><strong>{record.exerciseName}</strong><small>{metric.label} · {formatPersonalRecordDate(metric.dateKey)}</small></div><span><strong>{formatPersonalRecordMetric(metric, units)}</strong></span></article> }
function PersonalRecordsView({ records, units, onBack }: { records: ExercisePersonalRecords[]; units: ProgressSourceData['units']; onBack: () => void }) { const [query, setQuery] = useState(''); const filtered = useMemo(() => searchPersonalRecords(records, query), [records, query]); return <PageFrame className="page-stack progress-page personal-records-page"><header className="progress-subheader"><button className="back-button" type="button" aria-label="Back to Progress" onClick={onBack}><ArrowLeft aria-hidden="true" /></button><div><p className="eyebrow">Progress archive</p><h1>Personal Records</h1><p>Your best logged performances</p></div></header><label className="progress-search"><Search size={19} aria-hidden="true" /><span className="sr-only">Search personal records by exercise name</span><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search exercises…" /></label><p className="progress-search-count" aria-live="polite">{filtered.length} {filtered.length === 1 ? 'exercise' : 'exercises'}</p>{filtered.length ? <section className="personal-record-list" aria-label="Exercise personal records">{filtered.map((record) => <article className="panel personal-record-card" key={record.exerciseId}><header><div><p className="eyebrow">{trackingLabel(record.trackingType)}</p><h2>{record.exerciseName}</h2></div><Award aria-hidden="true" /></header><dl>{record.metrics.map((metric) => <div key={metric.key}><dt>{metric.label}</dt><dd><strong>{formatPersonalRecordMetric(metric, units)}</strong><small>{formatPersonalRecordDate(metric.dateKey)}</small></dd></div>)}</dl><p>Last PR · {formatPersonalRecordDate(record.lastPrDateKey)}</p></article>)}</section> : <Panel className="progress-records-empty"><h2>{records.length ? 'No matching records' : 'No personal records yet'}</h2><p>{records.length ? 'Try another exercise name.' : 'Complete measurable workout sets to establish records.'}</p></Panel>}</PageFrame> }
function trackingLabel(type: ExercisePersonalRecords['trackingType']) { return type.replaceAll('_', ' ') }
function formatNumber(value: number) { return new Intl.NumberFormat(undefined, { maximumFractionDigits: 1 }).format(Number.isFinite(value) ? value : 0) }
function formatCompact(value: number) { return new Intl.NumberFormat(undefined, { notation: value >= 10000 ? 'compact' : 'standard', maximumFractionDigits: 1 }).format(value) }
