/// <reference types="node" />
import assert from 'node:assert/strict'
import fs from 'node:fs'

const page = fs.readFileSync('src/features/settings/SettingsPage.tsx', 'utf8')
const css = fs.readFileSync('src/styles/app.css', 'utf8')
const battleMusic = fs.readFileSync('src/components/ui/BattleMusicDeck.tsx', 'utf8')

assert.match(page, /settings-modern-detail settings-appearance-detail/)
assert.match(page, /settings-modern-detail settings-units-detail/)
assert.match(page, /settings-modern-detail settings-audio-detail/)
assert.match(page, /settings-modern-detail settings-notifications-detail/)
assert.match(page, /settings-modern-detail settings-profile-detail/)
assert.match(page, /settings-modern-detail settings-backup-detail/)
assert.match(page, /settings-appearance-card/)
assert.match(page, /settings-units-card/)
assert.match(page, /settings-profile-card/)
assert.match(page, /Metric<br\s*\/?><small>kg · km<\/small>/)
assert.match(page, /Imperial<br\s*\/?><small>lb · mi<\/small>/)
assert.match(page, /const \[unitsNoteVisible, setUnitsNoteVisible\] = useState\(false\)/)
assert.match(page, /setUnitsNoteVisible\(true\)/)
assert.match(page, /unitsNoteVisible \? <p className="appearance-note units-canonical-note" role="status">Stored workout values stay canonical/)
assert.doesNotMatch(page, /Nutrition calculation inputs remain labelled in kilograms and centimetres in today’s data model\./)
assert.match(page, /Sound effects and battle music follow you throughout FitDex\./)
assert.match(page, /<summary>WHEN IT SENDS<\/summary>/)
assert.match(page, /notification-handheld-shell/)
assert.match(page, /notification-master-module/)
assert.match(page, /notification-category-module/)
assert.match(page, /notification-setting-row notification-toggle-row/)
assert.match(page, /notification-setting-row notification-reminder-row/)
assert.match(page, /notification-disclosure/)
assert.doesNotMatch(page, /notification-master-card|notification-section-card|notification-category-row|notification-time-row|notification-rule-note/)
assert.match(page, /nutrition-control-bay-shell/)
assert.match(page, /NutritionTargetsHeader/)
assert.match(page, /FITDEX \/\/ TARGET SYSTEM/)
assert.match(page, /<p className="eyebrow">Settings \/ Your System<\/p>/)
assert.match(page, /<h1>NUTRITION TARGETS<\/h1>/)
assert.match(page, /Daily energy &amp; protein configuration\./)
assert.match(page, /control-bay-formula-readout/)
assert.match(page, /control-bay-profile-stack/)
assert.match(page, /control-bay-telemetry-grid/)
assert.match(page, /Execute: Save Targets/)
assert.match(css, /\.settings-modern-detail\s*\{[^}]*--settings-detail-accent:\s*var\(--color-theme-accent\);[^}]*border-radius:\s*18px;/s)
assert.match(css, /\.settings-units-card \.settings-segmented(?:,\s*\.settings-appearance-card \.settings-segmented)?\s*\{[^}]*border-radius:\s*9px;/s)
assert.match(css, /\.settings-units-card \.appearance-note,\s*(?:\.settings-appearance-card \.appearance-note,\s*)?\.settings-audio \.appearance-note\s*\{[^}]*border-left:\s*3px solid var\(--settings-detail-accent\);[^}]*border-radius:\s*9px;/s)
assert.match(css, /\.units-canonical-note\s*\{[^}]*font-size:\s*\.72rem;[^}]*line-height:\s*1\.4;/s)
assert.match(page, /<BattleMusicDeck className="bgm-deck"/)
assert.match(page, /name="background-music"/)
assert.match(battleMusic, /BATTLE MUSIC/)
assert.match(battleMusic, /BGM DECK/)
assert.match(battleMusic, /MUSIC OFF/)
assert.match(battleMusic, /<PixelMuteIcon \/><b>ACTIVE<\/b>/)
assert.doesNotMatch(battleMusic, /<b>OFF<\/b>/)
assert.match(battleMusic, /viewBox="0 0 18 14"/)
assert.match(battleMusic, /AudioEqualizer/)
assert.match(css, /\.battle-music-deck\s*\{[^}]*border-radius:\s*10px;/s)
assert.match(css, /\.settings-audio \.bgm-deck\s*\{[^}]*--battle-music-accent:\s*var\(--settings-detail-accent\);/s)
assert.match(css, /\.battle-music-channel\.is-active\s*\{[^}]*border-color:\s*var\(--battle-music-accent\);/s)
assert.match(css, /\.battle-music-channel:has\(input:focus-visible\)/)
assert.match(css, /\.settings-notifications-detail \.notification-section-card\s*\{[^}]*border-radius:\s*12px;/s)
assert.match(css, /\.settings-notifications-detail \.notification-rule-note\s*\{[^}]*border-radius:\s*8px;/s)
assert.match(css, /\.settings-notifications-detail\s*\{[^}]*border-radius:\s*20px;[^}]*box-shadow:/s)
assert.match(css, /\.settings-notifications-detail \.notification-master-card\s*\{[^}]*border-top:\s*3px solid[^}]*border-left:\s*1px solid[^}]*border-radius:\s*14px;/s)
assert.match(css, /\.settings-notifications-detail \.notification-section-card\s*\{[^}]*border-radius:\s*13px;[^}]*box-shadow:/s)
assert.match(css, /\.settings-notifications-detail \.notification-category-row,\s*\.settings-notifications-detail \.notification-time-row\s*\{[^}]*border-radius:\s*9px;/s)
assert.match(css, /\.settings-notifications-detail \.notification-rule-note\s*\{[^}]*border-radius:\s*9px;/s)
assert.match(css, /\.notification-master-module,\s*\.notification-category-module\s*\{[^}]*border-radius:\s*14px;/s)
assert.match(css, /\.notification-master-control,\s*\.notification-setting-row\s*\{[^}]*border-radius:\s*9px;/s)
assert.match(css, /\.notification-disclosure\s*\{[^}]*border-radius:\s*9px;/s)
assert.match(css, /\.notification-time-dialog\s*\{[^}]*border-radius:\s*16px;[^}]*box-shadow:/s)
assert.match(css, /\.notification-time-dialog \.notification-time-fields select\s*\{[^}]*border-radius:\s*7px;/s)
assert.match(css, /\.notification-time-dialog \.settings-segmented\s*\{[^}]*border-radius:\s*9px;/s)
assert.match(css, /\.nutrition-targets-detail\.settings-modern-detail\s*\{[^}]*border:\s*3px solid var\(--color-border-strong\);/s)
assert.match(css, /\.nutrition-control-bay-screen\s*\{[^}]*border:\s*2px solid var\(--color-shadow\);/s)
assert.match(css, /\.nutrition-terminal-status\s*\{[^}]*border-bottom:\s*2px solid var\(--color-border\);/s)
assert.match(page, /id="nutrition-baseline"[\s\S]*?defaultExpanded=\{false\}/)
assert.match(page, /id="nutrition-energy"[\s\S]*?defaultExpanded=\{false\}/)
assert.match(css, /@media \(prefers-reduced-motion:\s*reduce\)\s*\{\s*\.control-bay-status\s*>\s*i\s*\{\s*animation:\s*none;\s*\}\s*\}/)
assert.match(css, /\.control-bay-telemetry-grid\s*\{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);/s)
assert.match(css, /\.control-bay-profile-stack\s*\{[^}]*grid-template-columns: minmax\(0, 1fr\);/s)
assert.doesNotMatch(css, /\.control-bay-profile-grid/)

const avatarSelector = fs.readFileSync('src/features/avatar/AvatarSelector.tsx', 'utf8')
assert.match(avatarSelector, /selected-avatar-detail" data-faction=\{selectedAvatar\.faction\}/)
assert.match(avatarSelector, /selected-avatar-content/)
assert.match(avatarSelector, /avatar-option(?: is-selected)?['"][\s\S]*?data-faction=\{avatar\.faction\}/)

assert.match(css, /\.selected-avatar-detail\s*\{[^}]*--selected-faction-accent:\s*var\(--color-faction-spartans\);[^}]*grid-template-columns:\s*auto minmax\(0,\s*1fr\);/s)
assert.match(css, /\.selected-avatar-detail\[data-faction='amazonians'\]\s*\{[^}]*--selected-faction-accent:\s*var\(--color-faction-amazonians\);/s)
assert.match(css, /\.avatar-group\[data-faction='spartans'\] legend/s)
assert.match(css, /\.avatar-group\[data-faction='amazonians'\] legend/s)
assert.match(css, /\.avatar-option\[data-faction='amazonians'\]\s*\{[^}]*--card-faction-accent:\s*var\(--color-faction-amazonians\);/s)

console.log('Settings detail UI assertions passed: shared shell, Units, Audio, Notifications, Avatar Selector faction styling, rounded controls, callouts, and theme tokens')
