/// <reference types="node" />
import assert from 'node:assert/strict'
import fs from 'node:fs'

const css = fs.readFileSync('src/styles/app.css', 'utf8')
const themeCss = fs.readFileSync('src/index.css', 'utf8')
const html = fs.readFileSync('index.html', 'utf8')
const vite = fs.readFileSync('vite.config.ts', 'utf8')
const database = fs.readFileSync('src/data/database.ts', 'utf8')
const home = fs.readFileSync('src/pages/HomePage.tsx', 'utf8')
const workoutPage = fs.readFileSync('src/pages/WorkoutPage.tsx', 'utf8')
const workoutSession = fs.readFileSync('src/features/workout/WorkoutSessionViews.tsx', 'utf8')
const exerciseDex = fs.readFileSync('src/features/exerciseDex/ExerciseDex.tsx', 'utf8')
const foodPage = fs.readFileSync('src/pages/FoodPage.tsx', 'utf8')
const progressPage = fs.readFileSync('src/pages/ProgressPage.tsx', 'utf8')
const journalPage = fs.readFileSync('src/pages/JournalPage.tsx', 'utf8')
const settingsPage = fs.readFileSync('src/features/settings/SettingsPage.tsx', 'utf8')
const pageFrame = fs.readFileSync('src/components/layout/PageFrame.tsx', 'utf8')
const avatar = fs.readFileSync('src/features/avatar/AvatarPortrait.tsx', 'utf8')
const weeklyPlan = fs.readFileSync('src/features/workout/WeeklyPlanViews.tsx', 'utf8')
const guide = fs.readFileSync('src/features/help/GuideDialog.tsx', 'utf8')
const appShell = fs.readFileSync('src/components/layout/AppShell.tsx', 'utf8')
const backup = fs.readFileSync('src/features/backup/BackupSettings.tsx', 'utf8')
const exerciseMedia = fs.readFileSync('src/features/exerciseMedia/ExerciseMediaSettings.tsx', 'utf8')
const onboarding = fs.readFileSync('src/features/onboarding/Onboarding.tsx', 'utf8')
const requiredName = fs.readFileSync('src/features/profile/RequiredDisplayNamePrompt.tsx', 'utf8')

assert.match(html, /width=device-width, initial-scale=1\.0, viewport-fit=cover/)
assert.doesNotMatch(vite, /orientation:/, 'The installed PWA must remain usable in phone landscape')
assert.match(vite, /globPatterns: \['\*\*\/\*\.\{js,css,html,svg,png,woff2\}'\]/)
assert.doesNotMatch(vite, /mp4/)
assert.doesNotMatch(appShell, /Offline ready/i)
assert.match(appShell, /navigator\.onLine/)
assert.match(appShell, /addEventListener\('online', updateOnline\)/)
assert.match(appShell, /addEventListener\('offline', updateOnline\)/)
assert.match(appShell, /!online \? <div className="connectivity-status" role="status" aria-live="polite"/)
assert.match(appShell, /Offline<\/div> : null/)
assert.match(appShell, /brandingForTheme\(family\)/)
assert.match(appShell, /wordmark-mobile-name/)
assert.match(pageFrame, /fitdex-page-frame/)
assert.match(home, /home-command-home fitdex-page-frame/)
assert.match(workoutPage, /<PageFrame className="workout-page workout-hub"/)
assert.match(foodPage, /<PageFrame className="page-stack food-page"/)
assert.match(progressPage, /<PageFrame className="page-stack progress-page"/)
assert.match(journalPage, /<PageFrame className="page-stack journal-page"/)
assert.match(settingsPage, /fitdex-page-frame page-stack settings-page settings-hub/)
assert.match(settingsPage, /fitdex-page-frame page-stack settings-page settings-detail-page/)
const pageFrameGeometry = css.match(/\.fitdex-page-frame \{([^}]*)\}/s)?.[1] ?? ''
assert.match(pageFrameGeometry, /padding: 8px/)
assert.match(pageFrameGeometry, /border: 4px solid var\(--color-border-strong\)/)
assert.match(pageFrameGeometry, /border-radius: 18px/)
assert.match(pageFrameGeometry, /background: color-mix\(in srgb, var\(--color-app-surface\) 92%, var\(--color-text\)\)/)
assert.doesNotMatch(pageFrameGeometry, /height:|overflow-y:/)

assert.doesNotMatch(themeCss, /(?:html|body) \{[^}]*min-width:/s, 'The document must not force overflow below the 320px robustness floor')
assert.match(themeCss, /input, textarea, select \{ min-width: 0; font-size: 1rem; \}/)
assert.match(themeCss, /textarea:focus-visible/)
assert.doesNotMatch(css, /width:\s*100vw/)
assert.doesNotMatch(css, /(?:^|[^sdl])100vh/)

assert.match(css, /\.app-frame \{[^}]*env\(safe-area-inset-bottom\)/s)
assert.match(css, /\.app-header \{[^}]*safe-area-inset-top[^}]*safe-area-inset-right[^}]*safe-area-inset-left/s)
assert.match(css, /\.app-main \{[^}]*safe-area-inset-right[^}]*safe-area-inset-left/s)
assert.match(css, /\.app-nav \{[^}]*safe-area-inset-bottom[^}]*safe-area-inset-right[^}]*safe-area-inset-left/s)
assert.match(css, /\.active-workout-final-actions \{[^}]*safe-area-inset-bottom/s)
assert.match(css, /\.app-frame\s*\{[^}]*--app-bottom-nav-height:\s*74px;/s)
assert.match(css, /@media\s*\(max-width:\s*700px\)[\s\S]*\.app-frame\s*\{[^}]*--app-bottom-nav-height:\s*68px;/s)
assert.match(css, /@media \(max-width: 700px\)[\s\S]*\.app-nav \{[^}]*min-height: calc\(64px \+ env\(safe-area-inset-bottom\)\)/s)
assert.match(css, /@media \(max-width: 700px\)[\s\S]*\.nav-item::before \{[^}]*width: 24px;[^}]*height: 3px/s)
assert.match(css, /\.active-workout-page \{[^}]*max-width: 480px[^}]*container: active-workout \/ inline-size/s)
assert.match(css, /\.active-workout-page \{[^}]*gap: 0/s)
assert.match(css, /@media \(max-width: 700px\)[\s\S]*\.app-main:has\(\.active-workout-page\) \{[^}]*padding: 0/s)
assert.match(css, /\.active-workout-final-actions \{[^}]*--app-bottom-nav-height[^}]*safe-area-inset-bottom/s)
assert.match(css, /\.food-dialog \{[^}]*100dvh[^}]*overflow-y: auto[^}]*overscroll-behavior: contain/s)
assert.match(css, /\.onboarding-card \{[^}]*100dvh/s)
assert.match(css, /\.onboarding-content \{[^}]*min-height: 0[^}]*overflow-y: auto/s)
assert.match(css, /\.step-rail button \{[^}]*height: 6px/s)
assert.match(css, /\.onboarding-actions \{[^}]*safe-area-inset-bottom/s)
assert.match(css, /\.profile-name-backdrop \{[^}]*safe-area-inset-top[^}]*safe-area-inset-bottom/s)
assert.match(css, /\.profile-name-prompt input \{[^}]*width: 100%[^}]*min-height: 52px/s)
assert.match(css, /\.home-hero-player-copy h1 \{[^}]*overflow-wrap: anywhere/s)
assert.match(requiredName, /maxLength=\{MAX_DISPLAY_NAME_LENGTH\}/)
assert.match(requiredName, /aria-live="polite"/)
assert.match(onboarding, /FitDex Field Guide/)
assert.match(onboarding, /Weekly Plan & Streaks/)
assert.match(onboarding, /Battle Music/)
assert.match(css, /\.home-music-controls button \{[^}]*min-height: 46px/s)
assert.match(css, /\.home-music-tracks button \{[^}]*min-width: 0[^}]*min-height: 42px/s)

assert.match(css, /@container\s*active-workout\s*\(max-width:\s*350px\)[\s\S]*\.session-stats-bar\s*\{[^}]*flex-wrap:\s*wrap;/s)
assert.match(css, /@media\s*\(max-width:\s*479px\)[\s\S]*\.routine-exercise-list\s*>\s*li\s*\{[^}]*grid-template-columns:\s*1fr;\s*\}/s)
assert.match(css, /@media\s*\(max-width:\s*374px\)[\s\S]*\.food-macros\s*\{[^}]*grid-template-columns:\s*repeat\(2,\s*minmax\(0,\s*1fr\)\);\s*\}/s)
assert.match(css, /@media \(min-width: 700px\)/)
assert.match(css, /@media \(min-width: 980px\)/)
assert.match(css, /@media \(min-width: 980px\)[\s\S]*\.app-frame \{[^}]*width: min\(1180px, calc\(100% - 48px\)\)/)
assert.match(css, /\.app-main\s*\{[^}]*max-width:\s*880px;/s)
assert.match(css, /\.connectivity-status \{[^}]*margin-left: auto;[^}]*color: var\(--color-secondary\)/s)

assert.match(css, /\.workout-hub-rows strong[^}]*overflow: hidden[^}]*text-overflow: ellipsis[^}]*white-space: nowrap/s)
assert.match(css, /\.workout-hub \{[^}]*max-width: 480px[^}]*container: workout-hub \/ inline-size/s)
assert.match(css, /\.workout-week-grid \{[^}]*repeat\(auto-fit, minmax\(48px, 1fr\)\)/s)
assert.match(css, /@container\s*workout-hub\s*\(max-width:\s*350px\)[\s\S]*\.workout-mission-actions,\s*\.workout-replace-dialog\s*>\s*div\s*\{[^}]*grid-template-columns:\s*1fr;\s*\}/s)
assert.match(css, /\.workout-hub-backdrop \{[^}]*safe-area-inset-right[^}]*safe-area-inset-bottom[^}]*safe-area-inset-left/s)
assert.match(workoutPage, /data-variant="mission-stack"/)
assert.match(workoutPage, /Weekly Schedule/)
assert.match(css, /\.exercise-header-title\s+strong,\s*\.active-exercise-heading\s+strong,\s*\.exercise-name\s*\{[^}]*overflow:\s*hidden;[^}]*text-overflow:\s*ellipsis;[^}]*white-space:\s*nowrap;/s)
assert.match(css, /\.exercise-category-card\s+strong\s*\{[^}]*overflow-wrap:\s*anywhere;/s)
assert.match(css, /\.exercise-row-main\s+strong\s*\{[^}]*overflow-wrap:\s*anywhere;/s)
assert.match(css, /\.food-entry-copy h2 \{[^}]*overflow-wrap: anywhere/s)
assert.match(css, /\.category-grid button span:last-child \{[^}]*overflow-wrap: anywhere/s)
assert.match(css, /\.custom-category-preview\s+strong\s*\{[^}]*overflow-wrap:\s*anywhere;/s)
assert.match(css, /\.home-hero-player-copy h1 \{[^}]*overflow-wrap: anywhere/s)
assert.match(home, /getGreetingPeriod\(now\)/)
assert.match(css, /@media\s*\(max-width:\s*374px\)[\s\S]*\.home-hero-player\s*\{[^}]*grid-template-columns:\s*62px\s+minmax\(0,\s*1fr\)\s+52px;/s)
assert.match(css, /@media\s*\(min-width:\s*701px\)[\s\S]*\.home-mobile-hero\s*\{[^}]*display:\s*none;\s*\}/s)
assert.match(css, /@media \(min-width: 701px\)[\s\S]*\.home-desktop-hero \{[^}]*grid-template-columns: auto minmax\(0, 1fr\)/)
assert.doesNotMatch(css, /\.mobile-home-faction/)
assert.match(css, /\.home-mobile-music-tracks \{[^}]*min-width: 0[^}]*border-block:/s)
assert.match(css, /\.home-mobile-music-tracks label \{[^}]*min-width: 0[^}]*min-height: 42px/s)
assert.match(css, /\.home-mobile-journal-gateway \{[^}]*width: 100%[^}]*min-width: 0/s)

assert.match(css, /\.routine-order-controls button \{[^}]*width: 44px;[^}]*height: 44px/s)
assert.match(css, /\.custom-category-delete \{[^}]*width: 44px;[^}]*height: 44px/s)
assert.match(css, /\.progress-period button \{[^}]*min-height: 44px/s)
assert.match(css, /\.home-quick-access button \{[^}]*min-height: 54px/s)
assert.match(workoutSession, /active-finish-btn/)
assert.match(workoutSession, /Finish Workout/)
assert.match(workoutSession, /DOOM_VICTORY_BANTERS/)
assert.match(exerciseDex, /exercise-picker-contextbar/)
assert.match(exerciseDex, /exercise-library-scope/)
assert.match(exerciseDex, /aria-label=\{`\$\{picker\.existingExerciseIds\.has\(exercise\.id\) \? 'Remove' : 'Add'\}/)
assert.match(exerciseDex, /role="alertdialog"/)
assert.match(foodPage, /food-breakdown-switch/)
assert.match(foodPage, /food-donut/)
assert.match(css, /@media\s*\(max-width:\s*599px\)[\s\S]*\.food-breakdown-body\s*\{[^}]*grid-template-columns:\s*1fr;/s)
assert.match(css, /\.exercise-row \{[^}]*grid-template-columns: minmax\(0, 1fr\) 44px 44px/s)
assert.match(css, /\.exercise-picker-contextbar \{[^}]*position: sticky[^}]*safe-area-inset-top/s)
assert.match(css, /\.exercise-dex-panel\.is-picker \.exercise-dex-heading \{[^}]*position: sticky/s)
assert.match(css, /\.workout-finish-backdrop \{[^}]*safe-area-inset-top[^}]*safe-area-inset-bottom[^}]*overflow-y: auto/s)
assert.match(css, /\.guide-backdrop \{[^}]*safe-area-inset-top[^}]*safe-area-inset-bottom/s)
assert.match(css, /\.guide-dialog \{[^}]*100dvh[^}]*overflow: hidden/s)
assert.match(css, /\.guide-content \{[^}]*min-height: 0[^}]*overflow-y: auto/s)
assert.match(css, /@media \(max-height: 480px\) and \(orientation: landscape\)/)
assert.match(css, /\.weekly-plan-list button \{[^}]*min-width: 0[^}]*grid-template-columns: 46px minmax\(0, 1fr\) auto/s)
assert.match(css, /@media\s*\(max-width:\s*599px\)[\s\S]*\.home-week-grid\s*\{[^}]*grid-template-columns:\s*repeat\(4,/s)
assert.match(weeklyPlan, /WEEKDAY_IDS\.map/)
assert.match(weeklyPlan, /No routines yet/)
assert.match(guide, /role="dialog" aria-modal="true"/)
assert.match(home, /No workout planned yet/)
assert.match(home, /Set Weekly Plan/)

assert.match(css, /\.exercise-detail-media img,\s*\.exercise-detail-media video\s*\{[^}]*width: 100%;[^}]*height: auto;[^}]*object-fit: contain/s)
assert.match(css, /\.avatar-portrait img\s*\{[^}]*object-fit:\s*contain;[^}]*image-rendering:\s*pixelated/s)
assert.match(css, /\.exercise-category-sprite\s*\{[^}]*object-fit:\s*contain;[^}]*image-rendering:\s*pixelated/s)
assert.match(css, /\.food-sprite\s*\{[^}]*image-rendering:\s*pixelated/s)
assert.match(css, /\.progress-chart\s*\{[^}]*min-width:\s*0;[^}]*overflow-x:\s*auto/s)
assert.match(css, /\.food-search input\s*\{[^}]*min-width:\s*0;[^}]*border:\s*0;[^}]*outline:\s*0/s)
assert.match(css, /\.food-search button:focus-visible\s*\{[^}]*outline:\s*2px solid var\(--color-focus\);/s)

assert.match(home, /<AvatarPortrait avatar=\{selectedAvatar\} size="medium" priority/)
assert.match(avatar, /loading=\{priority \? 'eager' : 'lazy'\}/)
assert.match(avatar, /fetchPriority=\{priority \? 'high' : 'auto'\}/)
assert.match(avatar, /width=\{384\}/)
assert.match(avatar, /height=\{576\}/)
assert.match(database, /DATABASE_SCHEMA_VERSION = 7/)
assert.match(css, /\.gamification-badge\s*\{[^}]*width:\s*62px;[^}]*height:\s*62px;/s)
assert.match(css, /\.gamification-badge\.is-large\s*\{[^}]*width:\s*108px;\s*height:\s*108px;/s)
assert.match(css, /@media\s*\(max-width:\s*374px\)[\s\S]*\.gamification-notification\s+\.gamification-badge\.is-large\s*\{[^}]*width:\s*88px;\s*height:\s*88px;/s)
assert.match(css, /@media\s*\(max-width:\s*374px\)[\s\S]*\.achievement-card\s*\{[^}]*grid-template-columns:\s*46px\s+minmax\(0,\s*1fr\)/s)
assert.match(css, /\.pause-dialog,\s*\.plan-change-dialog,\s*\.gamification-notification\s*\{[^}]*max-height:\s*calc\(100dvh - 32px\);[^}]*overflow:\s*auto;/s)
assert.match(css, /\.backup-dialog \{[^}]*width: min\(100%, 660px\);[^}]*100dvh[^}]*overflow-y: auto[^}]*overscroll-behavior: contain/s)
assert.match(css, /@media\s*\(max-width:\s*374px\)[\s\S]*\.backup-preview\s*>\s*div,\s*\.backup-complete-summary\s*>\s*div\s*\{[^}]*grid-template-columns:\s*1fr;/s)
assert.match(css, /@media\s*\(min-width:\s*600px\)[\s\S]*\.backup-dialog-actions-three\s*\{[^}]*grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\);\s*\}/s)
assert.match(backup, /selectedFilename/)
assert.match(backup, /backup-dialog-actions backup-dialog-actions-three/)
assert.match(backup, /Back Up Current Data First/)
assert.match(exerciseMedia, /Remove all exercise downloads\?/)
assert.match(exerciseMedia, /Exercise data, routines, and workout history are not affected\./)

console.log('Responsive UI assertions passed: fluid root, landscape-capable PWA, safe areas, dynamic-height dialogs, compact workout rows, wrapping, touch targets, media, charts, search focus, avatars, and precache safety')
