/// <reference types="node" />
import assert from 'node:assert/strict'
import fs from 'node:fs'

const css = fs.readFileSync('src/styles/app.css', 'utf8')
const themeCss = fs.readFileSync('src/index.css', 'utf8')
const html = fs.readFileSync('index.html', 'utf8')
const vite = fs.readFileSync('vite.config.ts', 'utf8')
const database = fs.readFileSync('src/data/database.ts', 'utf8')
const home = fs.readFileSync('src/pages/HomePage.tsx', 'utf8')
const workoutPage = fs.readFileSync('src/pages/WorkoutPage.tsx', 'utf8')
const workoutSession = fs.readFileSync('src/features/workout/WorkoutSessionViews.tsx', 'utf8')
const exerciseDex = fs.readFileSync('src/features/exerciseDex/ExerciseDex.tsx', 'utf8')
const foodPage = fs.readFileSync('src/pages/FoodPage.tsx', 'utf8')
const avatar = fs.readFileSync('src/features/avatar/AvatarPortrait.tsx', 'utf8')
const weeklyPlan = fs.readFileSync('src/features/workout/WeeklyPlanViews.tsx', 'utf8')
const guide = fs.readFileSync('src/features/help/GuideDialog.tsx', 'utf8')

assert.match(html, /width=device-width, initial-scale=1\.0, viewport-fit=cover/)
assert.doesNotMatch(vite, /orientation:/, 'The installed PWA must remain usable in phone landscape')
assert.match(vite, /globPatterns: \['\*\*\/\*\.\{js,css,html,svg,png,woff2\}'\]/)
assert.doesNotMatch(vite, /mp4/)

assert.doesNotMatch(themeCss, /(?:html|body) \{[^}]*min-width:/s, 'The document must not force overflow below the 320px robustness floor')
assert.match(themeCss, /input, textarea, select \{ min-width: 0; font-size: 1rem; \}/)
assert.match(themeCss, /textarea:focus-visible/)
assert.doesNotMatch(css, /width:\s*100vw/)
assert.doesNotMatch(css, /(?:^|[^sdl])100vh/)

assert.match(css, /\.app-frame \{[^}]*env\(safe-area-inset-bottom\)/s)
assert.match(css, /\.app-header \{[^}]*safe-area-inset-top[^}]*safe-area-inset-right[^}]*safe-area-inset-left/s)
assert.match(css, /\.app-main \{[^}]*safe-area-inset-right[^}]*safe-area-inset-left/s)
assert.match(css, /\.app-nav \{[^}]*safe-area-inset-bottom[^}]*safe-area-inset-right[^}]*safe-area-inset-left/s)
assert.match(css, /\.active-workout-final-actions \{[^}]*safe-area-inset-bottom/s)
assert.match(css, /\.app-frame \{ --app-bottom-nav-height: 74px;/)
assert.match(css, /\.active-workout-page \{[^}]*--workout-action-height[^}]*--app-bottom-nav-height[^}]*safe-area-inset-bottom/s)
assert.match(css, /\.active-workout-final-actions \{[^}]*--app-bottom-nav-height[^}]*safe-area-inset-bottom/s)
assert.match(css, /\.food-dialog \{[^}]*100dvh[^}]*overflow-y: auto[^}]*overscroll-behavior: contain/s)
assert.match(css, /\.onboarding-card \{[^}]*100dvh/s)
assert.match(css, /\.onboarding-content \{[^}]*min-height: 0[^}]*overflow-y: auto/s)

assert.match(css, /\.active-set-row \{[^}]*min-width: 0[^}]*gap: 7px[^}]*padding: 8px/s)
assert.match(css, /\.set-inputs \{[^}]*repeat\(auto-fit, minmax\(112px, 1fr\)\)/s)
assert.match(css, /@media \(max-width: 339px\)[\s\S]*\.set-inputs \{ grid-template-columns: 1fr; \}/)
assert.match(css, /@media \(max-width: 479px\)[\s\S]*\.routine-exercise-list > li \{ grid-template-columns: 1fr; \}/)
assert.match(css, /@media \(max-width: 374px\)[\s\S]*\.food-macros \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); \}/)
assert.match(css, /@media \(min-width: 700px\)/)
assert.match(css, /@media \(min-width: 980px\)/)
assert.match(css, /@media \(min-width: 980px\)[\s\S]*\.app-frame \{[^}]*width: min\(1180px, calc\(100% - 48px\)\)/)
assert.match(css, /\.app-main \{ max-width: 880px;/)

assert.match(css, /\.routine-card-list strong[^}]*overflow-wrap: anywhere/s)
assert.match(css, /\.active-exercise-heading strong \{ overflow-wrap: anywhere; \}/)
assert.match(css, /\.exercise-category-card strong \{ overflow-wrap: anywhere;/)
assert.match(css, /\.exercise-row-main strong \{ overflow-wrap: anywhere;/)
assert.match(css, /\.food-entry-copy h2 \{[^}]*overflow-wrap: anywhere/s)
assert.match(css, /\.category-grid button span:last-child \{[^}]*overflow-wrap: anywhere/s)
assert.match(css, /\.custom-category-preview strong \{ overflow-wrap: anywhere;/)
assert.match(css, /\.home-hero h1 \{[^}]*overflow-wrap: anywhere/s)
assert.match(home, /formatHomeGreeting\(displayName, now\)/)

assert.match(css, /\.routine-order-controls button \{[^}]*width: 44px; height: 44px/s)
assert.match(css, /\.set-rest-button, \.set-remove-button \{[^}]*min-height: 44px[\s\S]*\.set-rest-button \{[^}]*min-width: 64px/s)
assert.match(css, /\.set-remove-button \{ width: 44px; height: 44px;/)
assert.match(css, /\.custom-category-delete \{[^}]*width: 44px;[^}]*height: 44px/s)
assert.match(css, /\.progress-period button \{[^}]*min-height: 44px/s)
assert.match(css, /\.home-quick-access button \{[^}]*min-height: 54px/s)
assert.match(css, /\.active-workout-top-actions button \{[^}]*min-height: 44px/s)
assert.match(workoutSession, /active-workout-top-actions/)
assert.match(workoutSession, /Pause workout timer/)
assert.match(workoutSession, /Add exercise/)
assert.match(workoutSession, /sets logged/)
assert.match(workoutSession, /workout-finish-backdrop/)
assert.doesNotMatch(workoutSession, /set-complete-button|toggleComplete/)
assert.match(workoutPage, /routine-top-add/)
assert.match(exerciseDex, /exercise-picker-contextbar/)
assert.match(exerciseDex, /exercise-library-scope/)
assert.match(exerciseDex, /aria-label=\{`\$\{picker\.existingExerciseIds\.has\(exercise\.id\) \? 'Remove' : 'Add'\}/)
assert.match(exerciseDex, /role="alertdialog"/)
assert.match(foodPage, /food-breakdown-switch/)
assert.match(foodPage, /food-donut/)
assert.match(css, /@media \(max-width: 599px\)[\s\S]*\.food-breakdown-body \{ grid-template-columns: 1fr; \}/)
assert.match(css, /\.exercise-row \{[^}]*grid-template-columns: minmax\(0, 1fr\) 52px/s)
assert.match(css, /\.exercise-picker-contextbar \{[^}]*position: sticky[^}]*safe-area-inset-top/s)
assert.match(css, /\.exercise-dex-panel\.is-picker \.exercise-dex-heading \{[^}]*position: sticky/s)
assert.match(css, /\.workout-finish-backdrop \{[^}]*safe-area-inset-top[^}]*safe-area-inset-bottom[^}]*overflow-y: auto/s)
assert.match(css, /\.guide-backdrop \{[^}]*safe-area-inset-top[^}]*safe-area-inset-bottom/s)
assert.match(css, /\.guide-dialog \{[^}]*100dvh[^}]*overflow: hidden/s)
assert.match(css, /\.guide-content \{[^}]*min-height: 0[^}]*overflow-y: auto/s)
assert.match(css, /@media \(max-height: 480px\) and \(orientation: landscape\)/)
assert.match(css, /\.weekly-plan-list button \{[^}]*min-width: 0[^}]*grid-template-columns: 46px minmax\(0, 1fr\) auto/s)
assert.match(css, /@media \(max-width: 599px\)[\s\S]*\.home-week-grid \{ grid-template-columns: repeat\(4,/)
assert.match(weeklyPlan, /WEEKDAY_IDS\.map/)
assert.match(weeklyPlan, /No routines yet/)
assert.match(guide, /role="dialog" aria-modal="true"/)
assert.match(home, /No workout planned yet/)
assert.match(home, /Set Weekly Plan/)

assert.match(css, /\.exercise-detail-media img, \.exercise-detail-media video \{[^}]*width: 100%;[^}]*height: auto;[^}]*object-fit: contain/s)
assert.match(css, /\.avatar-portrait img \{[^}]*object-fit: contain;[^}]*image-rendering: pixelated/s)
assert.match(css, /\.exercise-category-sprite \{[^}]*object-fit: contain;[^}]*image-rendering: pixelated/s)
assert.match(css, /\.food-sprite \{[^}]*image-rendering: pixelated/s)
assert.match(css, /\.progress-chart \{[^}]*min-width: 0;[^}]*overflow-x: auto/s)
assert.match(css, /\.food-search input \{[^}]*min-width: 0;[^}]*border: 0;[^}]*outline: 0/s)
assert.match(css, /\.food-search button:focus-visible \{ outline: 2px solid var\(--color-focus\);/)

assert.match(home, /<AvatarPortrait avatar=\{selectedAvatar\} size="medium" priority/)
assert.match(avatar, /loading=\{priority \? 'eager' : 'lazy'\}/)
assert.match(avatar, /fetchPriority=\{priority \? 'high' : 'auto'\}/)
assert.match(avatar, /width=\{384\}/)
assert.match(avatar, /height=\{576\}/)
assert.match(database, /DATABASE_SCHEMA_VERSION = 6/)

console.log('Responsive UI assertions passed: fluid root, landscape-capable PWA, safe areas, dynamic-height dialogs, compact workout rows, wrapping, touch targets, media, charts, search focus, avatars, and precache safety')
