/// <reference types="node" />
import assert from 'node:assert/strict'
import fs from 'node:fs'

const packageJson = JSON.parse(fs.readFileSync('package.json', 'utf8')) as { version: string; dependencies: Record<string, string>; devDependencies: Record<string, string>; scripts: Record<string, string> }
const capacitor = fs.readFileSync('capacitor.config.ts', 'utf8')
const vite = fs.readFileSync('vite.config.ts', 'utf8')
const main = fs.readFileSync('src/main.tsx', 'utf8')
const manifest = fs.readFileSync('android/app/src/main/AndroidManifest.xml', 'utf8')
const appGradle = fs.readFileSync('android/app/build.gradle', 'utf8')
const capacitorPlugins = fs.readFileSync('android/app/src/main/assets/capacitor.plugins.json', 'utf8')

assert.match(capacitor, /appId: 'com\.fitdex\.app'/)
assert.match(capacitor, /appName: 'FitDex'/)
assert.match(capacitor, /webDir: 'dist'/)
assert.doesNotMatch(capacitor, /server:\s*\{/)
assert.equal(packageJson.dependencies['@capacitor/core'], '^8.5.0')
assert.equal(packageJson.dependencies['@capacitor/filesystem'], '^8.1.3')
assert.equal(packageJson.dependencies['@capacitor/file-transfer'], '^2.0.5')
assert.match(packageJson.dependencies['@capacitor/app'], /^\^8\./)
assert.equal(packageJson.devDependencies['@capacitor/cli'], '^8.5.0')
assert.equal(packageJson.devDependencies['@capacitor/android'], '^8.5.0')
assert.equal(packageJson.scripts['prepare:android-dist'], 'node scripts/prepare-android-dist.mjs')
assert.equal(packageJson.scripts['android:sync'], 'npm run build && npm run prepare:android-dist && npx cap sync android')
assert.match(packageJson.scripts['android:build'], /gradlew clean assembleDebug/)
assert.ok(fs.existsSync('android/app/src/main/AndroidManifest.xml'))
assert.match(manifest, /android:allowBackup="false"/)
assert.doesNotMatch(manifest, /usesCleartextTraffic="true"/)
assert.match(manifest, /orientation\|keyboardHidden\|keyboard\|screenSize/)
assert.match(appGradle, /namespace = "com\.fitdex\.app"/)
assert.match(appGradle, /applicationId "com\.fitdex\.app"/)
const mainActivity = fs.readFileSync('android/app/src/main/java/com/fitdex/app/MainActivity.java', 'utf8')
assert.match(mainActivity, /package com\.fitdex\.app;/)
assert.ok(!fs.existsSync('android/app/src/main/java/com/arijitbhaduri/fitdex/MainActivity.java'))
assert.match(appGradle, new RegExp(`versionName "${packageJson.version}"`))
assert.match(vite, /VitePWA\(/)
assert.match(vite, /injectRegister: false/)
assert.match(main, /Capacitor\.isNativePlatform\(\)/)
assert.match(main, /registerSW\(\{ immediate: true \}\)/)
for (const asset of ['fitdex-logo-spartan.png', 'fitdex-logo-amazonian.png', 'fitdex-icon-spartan.png', 'fitdex-icon-amazonian.png']) assert.ok(fs.existsSync(`public/branding/${asset}`))
assert.match(vite, /branding\/fitdex-icon-spartan\.png/)
assert.match(manifest, /android:icon="@mipmap\/ic_launcher_spartan"/)
assert.match(manifest, /android:name="\.SpartanLauncher"/)
assert.match(manifest, /android:name="\.AmazonianLauncher"/)
assert.match(manifest, /android:targetActivity="\.MainActivity"/)
assert.match(manifest, /android:enabled="true"[\s\S]*android:icon="@mipmap\/ic_launcher_spartan"[\s\S]*android.intent.category.LAUNCHER/)
assert.match(manifest, /android:enabled="false"[\s\S]*android:icon="@mipmap\/ic_launcher_amazonian"[\s\S]*android.intent.category.LAUNCHER/)
assert.ok(fs.existsSync('android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_spartan.xml'))
assert.ok(fs.existsSync('android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_amazonian.xml'))
assert.ok(fs.existsSync('android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_spartan_foreground.png'))
assert.ok(fs.existsSync('android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_amazonian_foreground.png'))
const spartanAdaptive = fs.readFileSync('android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_spartan.xml', 'utf8')
const amazonianAdaptive = fs.readFileSync('android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_amazonian.xml', 'utf8')
const launcherBackgrounds = fs.readFileSync('android/app/src/main/res/values/ic_launcher_background.xml', 'utf8')
assert.match(spartanAdaptive, /@color\/ic_launcher_spartan_background/)
assert.match(amazonianAdaptive, /@color\/ic_launcher_amazonian_background/)
assert.match(launcherBackgrounds, /ic_launcher_spartan_background">#0B111B/)
assert.match(launcherBackgrounds, /ic_launcher_amazonian_background">#291126/)
const launcherPlugin = fs.readFileSync('android/app/src/main/java/com/fitdex/app/LauncherBrandingPlugin.java', 'utf8')
assert.match(launcherPlugin, /@CapacitorPlugin\(name = "LauncherBranding"\)/)
assert.match(launcherPlugin, /SpartanLauncher/)
assert.match(launcherPlugin, /AmazonianLauncher/)
assert.match(launcherPlugin, /DONT_KILL_APP/)
assert.match(mainActivity, /registerPlugin\(LauncherBrandingPlugin\.class\)/)
assert.match(capacitorPlugins, /FileTransferPlugin/)
assert.match(capacitorPlugins, /FilesystemPlugin/)
assert.match(capacitorPlugins, /AppPlugin/)

console.log('Capacitor Android assertions passed: packaged dist config, matching v8 packages, Android shell, private backup policy, version alignment, browser-only PWA registration, and theme-aware launcher aliases')
