/// <reference types="node" />
import assert from 'node:assert/strict'
import fs from 'node:fs'

const page = fs.readFileSync('src/pages/WorkoutPage.tsx', 'utf8')
const exerciseDex = fs.readFileSync('src/features/exerciseDex/ExerciseDex.tsx', 'utf8')
const sessionViews = fs.readFileSync('src/features/workout/WorkoutSessionViews.tsx', 'utf8')
const repository = fs.readFileSync('src/features/workout/workoutRepository.ts', 'utf8')
const css = fs.readFileSync('src/styles/app.css', 'utf8')

const todayIndex = page.indexOf('today-mission-title')
const weeklyIndex = page.indexOf('weekly-plan-title')
const routinesIndex = page.indexOf('saved-routines-title')
const libraryIndex = page.indexOf('workout-dex-gateway')
const recentIndex = page.indexOf('recent-workouts-title')
assert.ok(todayIndex >= 0 && todayIndex < weeklyIndex && weeklyIndex < routinesIndex && routinesIndex < libraryIndex && libraryIndex < recentIndex)

assert.match(page, /No routines yet/)
assert.match(page, /No completed workouts yet/)
assert.match(page, /data-variant="mission-stack"/)
assert.match(page, /WEEKDAY_IDS\.map/)
assert.match(page, /is-today/)
assert.match(page, /How Workouts Work/)
assert.match(page, /Today's mission/)
assert.match(page, /No workout planned/)
assert.match(page, /Workout Day/)
assert.match(page, /Start empty workout/)
assert.match(page, /Workout in progress/)
assert.match(page, /Resume Workout/)
assert.match(page, /Other Options/)
assert.match(page, /Timer paused/)
assert.match(page, /Pause Workout Timer/)
assert.match(page, /Resume Workout Timer/)
assert.match(page, /Discard Current &amp; Choose Routine/)
assert.match(page, /Discard Current &amp; Open Workout/)
assert.match(page, /role="alertdialog"/)
assert.match(page, /discardWorkout\(activeWorkoutId\)/)
assert.match(page, /await discardWorkout[\s\S]*await begin/)
assert.match(page, /startWorkoutFromRoutine/)
assert.match(page, /startEmptyWorkout/)
assert.match(page, /Today's Plan/)
assert.match(page, /listRecentWorkouts/)
assert.match(page, /loadGamificationDashboard/)
assert.match(page, /Level \{gamification\.progression\.level\}/)
assert.doesNotMatch(page, /Rank VII|RANK \{gamification\.progression\.level\}/i)
assert.match(page, /<BookOpen size=\{20\}/)
assert.doesNotMatch(page, /className="app-nav"/)
assert.match(page, /overlayOpen \|\| view !== 'hub'/)
assert.match(page, /if \(replacementIntent\)[\s\S]*else if \(routineChooserOpen\)[\s\S]*else if \(quickLaunchOpen\)/)
assert.doesNotMatch(page, /May 20|fake routine|demo workout/i)
assert.match(page, /<ExerciseDex onAddToRoutine=/)
assert.match(page, /<ExerciseDex picker=/)
assert.match(page, /existingExerciseIds/)
assert.match(page, /onAddExercise/)
assert.match(page, /targetLabel: 'routine'/)
assert.match(page, /Back to Workout Hub/)
assert.match(page, /routine-top-add/)
assert.match(page, /MIN_PLANNED_SETS/)
assert.match(page, /MAX_PLANNED_SETS/)
assert.match(page, /ArrowUp/)
assert.match(page, /ArrowDown/)
assert.match(page, /Completed workout snapshots will remain untouched/)
assert.match(page, /<ActiveWorkoutView/)
assert.match(page, /<CompletedWorkoutDetail/)
assert.match(page, /recent-workout-delete/)
assert.match(page, /<WorkoutDeleteDialog/)

assert.match(sessionViews, /Add to today's workout/)
assert.match(sessionViews, /Pause workout timer/)
assert.match(sessionViews, /Resume workout timer/)
assert.match(sessionViews, /active-workout-top-actions/)
assert.match(sessionViews, /getWorkoutDuration/)
assert.match(sessionViews, /<SetValueInput/)
assert.match(sessionViews, /key=\{set\.id\}/)
assert.match(sessionViews, /sets logged/)
assert.match(sessionViews, /getWorkoutSetLogState/)
assert.match(sessionViews, /persistCurrentDrafts/)
assert.match(sessionViews, /FinishValidationDialog/)
assert.match(sessionViews, /Start rest timer after set/)
assert.match(sessionViews, /if \(wasRunning\)[\s\S]*pauseWorkout\(workoutId, Date\.now\(\)\)[\s\S]*persistCurrentDrafts/)
assert.match(sessionViews, /if \(finishWasRunning\) await resumeWorkout/)
assert.doesNotMatch(sessionViews, /toggleComplete|set-complete-button|Mark incomplete|Complete set/i)
assert.match(sessionViews, /Finish workout/)
assert.match(sessionViews, /Discard workout/)
assert.match(sessionViews, /DEFAULT_REST_SECONDS/)
assert.match(sessionViews, /getPreviousPerformance/)
assert.match(sessionViews, /inputMode="decimal"/)
assert.match(sessionViews, /inputMode="numeric"/)
assert.match(sessionViews, /Legacy incomplete row/)
assert.match(sessionViews, /set-row-heading/)
assert.match(sessionViews, /set-row-actions/)
assert.match(sessionViews, /✓ Logged/)
assert.match(sessionViews, /○ Incomplete/)
assert.match(sessionViews, /○ Empty/)
assert.doesNotMatch(sessionViews, /className="set-remove-button"/)
assert.match(sessionViews, /Delete set \{item\.sets\.length\}/)
assert.match(sessionViews, /role="alertdialog"/)
assert.match(sessionViews, /This cannot be undone/)
assert.match(sessionViews, /completed-workout-delete/)
assert.match(sessionViews, /is-current/)
assert.match(sessionViews, /is-active-set/)
assert.match(sessionViews, /activeSetIndex = unloggedIndex === -1 \? undefined : unloggedIndex/)
assert.match(sessionViews, /exercise-menu-trigger/)
assert.match(sessionViews, /exercise-context-menu/)
assert.match(sessionViews, /previous-copy-btn/)
assert.match(sessionViews, /handleCopyPrevious/)
assert.match(sessionViews, /active-workout-title-row/)
assert.match(sessionViews, /active-workout-rename-btn/)
assert.match(sessionViews, /session-header/)
assert.match(sessionViews, /session-hub-link/)
assert.match(sessionViews, /session-state-badge/)
assert.match(sessionViews, /state-pulse/)
assert.match(sessionViews, /session-title/)
assert.match(sessionViews, /session-stats-bar/)
assert.match(sessionViews, /stat-duration/)
assert.match(sessionViews, /stat-progress/)
assert.match(sessionViews, /pause-toggle-btn/)
assert.doesNotMatch(sessionViews.match(/pause-toggle-btn[\s\S]*?<\/button>/)?.[0] ?? '', /setRest/)
assert.match(sessionViews, /rest-timer-dock/)
assert.match(sessionViews, /rest-timer-pill/)
assert.match(sessionViews, /rest-time-display/)
assert.match(sessionViews, /timer-pill-btn/)
assert.match(sessionViews, /current === undefined \|\| current <= 1 \? undefined : current - 1/)
assert.match(sessionViews, /current === undefined \|\| current <= 15 \? undefined : current - 15/)
assert.match(sessionViews, /btn-bottom-secondary/)
assert.match(sessionViews, /btn-bottom-primary/)
assert.doesNotMatch(sessionViews, /<p className="eyebrow">\{timerPaused \?/)
assert.doesNotMatch(sessionViews.match(/active-workout-top-actions[\s\S]*?<\/div>/)?.[0] ?? '', /Add exercise|Finish workout/)
assert.match(sessionViews.match(/active-workout-final-actions[\s\S]*?<\/div>/)?.[0] ?? '', /Add exercise[\s\S]*Finish workout/)
assert.equal((sessionViews.match(/className="secondary-button btn-bottom-secondary"/g) ?? []).length, 1)
assert.equal((sessionViews.match(/className="primary-button btn-bottom-primary"/g) ?? []).length, 1)
assert.match(sessionViews, /exercise-header-title active-exercise-heading[\s\S]*className="exercise-name"[\s\S]*exercise-tag/)
assert.match(sessionViews, /metric-label-long[\s\S]*metric-label-short/)
assert.match(sessionViews, /exerciseCategorySnapshot, exerciseEquipment\.get\(item\.exercise\.exerciseId\)[\s\S]*join\(' · '\)/)
assert.match(sessionViews, /layoutClass=\{isDualMetric \? 'dual-metric' : 'single-metric'\}/)
assert.match(sessionViews, /disabled=\{logState === 'logged'\}/)
assert.match(sessionViews, /`\$\{displayWeight\(previous\.weight, units\)\} × \$\{previous\.reps\}`/)
assert.match(sessionViews, /onStartRest=\{\(\) => setRest\(DEFAULT_REST_SECONDS\)\}/)
assert.match(sessionViews, /if \(logState === 'logged'\) \{[\s\S]*?onStartRest\(\)/)
assert.match(repository, /deleteCompletedWorkout/)
assert.match(repository, /db\.transaction\('rw', db\.workouts, db\.workoutExercises, db\.workoutSets/)
assert.match(repository, /workout\.status !== 'completed'/)

assert.match(exerciseDex, /export interface ExerciseDexPicker/)
assert.match(exerciseDex, /onAddToRoutine\?: \(exercise: Exercise\) => void/)
assert.match(exerciseDex, /Add to routine/)
assert.match(exerciseDex, /exercise-picker-toggle/)
assert.match(exerciseDex, /exercise-picker-contextbar/)
assert.match(exerciseDex, />Added</)
assert.match(exerciseDex, /picker\.existingExerciseIds/)
assert.doesNotMatch(exerciseDex, /selectedExerciseIds/)

assert.match(css, /\.workout-hub \{[^}]*max-width: 480px[^}]*container: workout-hub \/ inline-size/s)
assert.match(css, /\.workout-hub-stack \{[^}]*display: grid;[^}]*min-width: 0/s)
assert.match(css, /\.workout-mission-card \{[^}]*border: 2px solid var\(--color-primary\)/s)
assert.match(css, /\.workout-mission-actions \{[^}]*minmax\(0, 1\.55fr\) minmax\(0, 1fr\)/s)
assert.match(css, /\.workout-week-grid \{[^}]*repeat\(auto-fit, minmax\(48px, 1fr\)\)/s)
assert.match(css, /@container\s*workout-hub\s*\(max-width:\s*350px\)[\s\S]*\.workout-mission-actions,\s*\.workout-replace-dialog\s*>\s*div\s*\{[^}]*grid-template-columns:\s*1fr;/s)
assert.match(css, /\.workout-hub-backdrop \{[^}]*safe-area-inset-bottom[^}]*overflow-y: auto/s)
assert.match(css, /\.workout-hub-rows strong \{[^}]*text-overflow: ellipsis[^}]*white-space: nowrap/s)
assert.match(css, /\.active-set-row\.is-logged \{[^}]*var\(--color-success\)/s)
assert.match(css, /\.active-workout-final-actions \{[^}]*position: sticky;/s)
assert.match(css, /\.set-row-actions \{[^}]*display: flex;/s)
assert.match(css, /\.set-table-header\.dual-metric,\s*\.proto-set-row\.dual-metric,\s*\.active-set-row\.dual-metric\s*\{[^}]*grid-template-columns:\s*var\(--workout-dual-grid\)/s)
assert.match(css, /\.set-table-header\.single-metric,\s*\.proto-set-row\.single-metric,\s*\.active-set-row\.single-metric\s*\{[^}]*grid-template-columns:\s*var\(--workout-single-grid\)/s)
assert.match(css, /@media\s*\(max-width:\s*479px\)[\s\S]*\.routine-exercise-list\s*>\s*li\s*\{[^}]*grid-template-columns:\s*1fr;/s)
assert.doesNotMatch(css, /\.active-set-row \.set-remove-button/)
assert.match(css, /\.workout-finish-backdrop \{[^}]*position: fixed[\s\S]*\.workout-finish-backdrop\s*>\s*section \{[^}]*100dvh/s)
assert.match(css, /\.active-workout-final-actions \{[^}]*env\(safe-area-inset-bottom\)/s)
assert.match(css, /\.active-workout-page \{[^}]*max-width: 480px[^}]*container: active-workout \/ inline-size/s)
assert.match(css, /\.active-workout-page \{[^}]*gap: 0/s)
assert.match(css, /@container\s*active-workout\s*\(max-width:\s*350px\)[\s\S]*\.metric-label-long\s*\{[^}]*display:\s*none;\s*\}[\s\S]*\.session-stats-bar\s*\{[^}]*flex-wrap:\s*wrap;/s)
assert.match(css, /\.set-action-btn \{[^}]*width: 100%[^}]*height: 42px/s)
assert.match(css, /\.app-main:has\(\.active-workout-page\) \{[^}]*padding: 0/s)
assert.match(css, /\.exercise-picker-contextbar \{[^}]*position: sticky;/s)
assert.match(css, /\.active-workout-top-actions button \{[^}]*min-height: 44px/s)
assert.doesNotMatch(css, /\.active-exercise-heading \{ min-height: 62px;/)
assert.match(css, /@media\s*\(max-width:\s*339px\)[\s\S]*\.set-inputs\s*\{[^}]*grid-template-columns:\s*1fr;/s)
assert.match(css, /\.recent-workout-delete \{[^}]*min-height: 52px/s)
assert.doesNotMatch(css.match(/\.workout-hub \{[\s\S]*?\.routine-choice-list/)?.[0] ?? '', /#[0-9a-f]{3,8}/i)

console.log('Workout UI assertions passed: Mission Stack states, guarded replacement, real data flows, responsive overlays, and theme tokens')
