/// <reference types="node" />
import assert from 'node:assert/strict'
import fs from 'node:fs'

const page = fs.readFileSync('src/pages/WorkoutPage.tsx', 'utf8')
const exerciseDex = fs.readFileSync('src/features/exerciseDex/ExerciseDex.tsx', 'utf8')
const sessionViews = fs.readFileSync('src/features/workout/WorkoutSessionViews.tsx', 'utf8')
const repository = fs.readFileSync('src/features/workout/workoutRepository.ts', 'utf8')
const css = fs.readFileSync('src/styles/app.css', 'utf8')
const plannerModal = fs.readFileSync('src/features/workout/WeeklyPlannerModal.tsx', 'utf8')

const weeklyIndex = page.indexOf('weekly-plan-title')
const libraryIndex = page.indexOf('workout-dex-gateway')
const todayIndex = page.indexOf('today-mission-title')
assert.ok(weeklyIndex >= 0 && weeklyIndex < libraryIndex && libraryIndex < todayIndex, 'Weekly Plan must be at top, followed by Exercise Dex, then Workout section')

// Main hub has removed standalone saved routines list in favor of day-based schedule
assert.doesNotMatch(page, /aria-labelledby="saved-routines-title"/, 'No separate Saved Routines section on main hub')

// Compact 7-day strip contract
assert.match(page, /workout-week-strip-compact/, 'Compact single-row 7-day strip must exist')
assert.match(page, /day-strip-pill/, 'Day strip pill buttons must exist')
assert.match(page, /is-rest/, 'Rest day indicator must exist')
assert.match(page, /is-workout/, 'Workout day indicator must exist')

// Hub directs user to Plan Week for schedule management
assert.match(page, /Click on the Plan Week button to plan your workout/, 'Hub directs user to plan week')
assert.match(page, /<WeeklyPlannerModal/, 'WeeklyPlannerModal must be wired into hub')
assert.match(plannerModal, /planner-close-btn/, 'WeeklyPlannerModal must have planner-close-btn')
assert.match(plannerModal, /cmd-icon-btn/, 'Close button must use cmd-icon-btn styling')
assert.match(css, /\.workout-week-strip-compact\s*\{[^}]*grid-template-columns:\s*repeat\(7,\s*1fr\)/s)
assert.match(css, /\.day-strip-pill\s*\{[^}]*border-radius:\s*0/s, 'Day strip pills must have square corners')
assert.match(css, /\.weekly-planner-overlay\s*\{[^}]*position:\s*fixed[^}]*height:\s*100dvh/s, 'Weekly planner must take full screen')

assert.match(page, /data-variant="mission-stack"/)
assert.match(page, /WEEKDAY_IDS\.map/)
assert.match(page, /is-today/)
assert.match(page, /How Workouts Work/)
assert.match(page, /Today's mission/)
assert.match(page, /No workout planned/)
assert.match(page, /Workout Day/)
assert.match(page, /Workout in progress/)
assert.match(page, /Resume Workout/)
assert.match(page, /Discard Workout/)
assert.doesNotMatch(page, /Timer paused|Pause Workout Timer|Resume Workout Timer/, 'The manual workout timer (pause/resume) has been removed — workouts run passively from start to finish')
assert.doesNotMatch(page, /isWorkoutTimerPaused|pauseWorkout|resumeWorkout/)
assert.match(page, /startWorkoutFromRoutine/)
assert.match(page, /startEmptyWorkout/)
assert.match(page, /loadGamificationDashboard/)
assert.match(page, /Level \{gamification\.progression\.level\}/)
assert.doesNotMatch(page, /Rank VII|RANK \{gamification\.progression\.level\}/i)
assert.match(page, /<BookOpen size=\{20\}/)
assert.doesNotMatch(page, /className="app-nav"/)
assert.match(page, /overlayOpen \|\| view !== 'hub'/)
assert.doesNotMatch(page, /May 20|fake routine|demo workout/i)
assert.match(page, /Back to Workout Hub/)
assert.match(page, /<ActiveWorkoutView/)
assert.match(page, /<CompletedWorkoutDetail/)
assert.match(sessionViews, /deleteWorkoutSummary|confirmDelete/)
assert.match(sessionViews, /<WorkoutDeleteDialog/)

assert.match(sessionViews, /LEVEL CLEARED|MISSION ACCOMPLISHED/)
assert.match(sessionViews, /DOOM_VICTORY_BANTERS/)
assert.match(sessionViews, /doom-victory-page/)
assert.doesNotMatch(sessionViews, /history-set-list|Legacy incomplete row/, 'Per-set logging rows removed from completed victory screen')
assert.match(sessionViews, /getWorkoutSetLogState/)
assert.doesNotMatch(sessionViews, /toggleComplete|set-complete-button|Mark incomplete|Complete set/i)
assert.match(sessionViews, /Discard workout/)
assert.match(sessionViews, /DEFAULT_REST_SECONDS/)
assert.match(sessionViews, /className="rest-toggle-btn secondary-button"/)
assert.match(sessionViews, />\s*Start Rest\s*</)
assert.match(sessionViews, /loggedSets > 0[\s\S]*?setRest\(DEFAULT_REST_SECONDS\)/)
assert.doesNotMatch(sessionViews, /className="set-remove-button"/)
// The dropdown menu only keeps notes and removal; set deletion and reordering have been removed.
assert.doesNotMatch(sessionViews, /Delete set \{item\.sets\.length\}/)
assert.doesNotMatch(sessionViews, /Move up|Move down/)
assert.doesNotMatch(sessionViews, /\+ Add session notes|\+ Add exercise/)
assert.match(sessionViews, /role="alertdialog"/)
assert.match(sessionViews, /This cannot be undone/)
assert.match(sessionViews, /completed-workout-delete/)
assert.match(sessionViews, /is-current/)
assert.match(sessionViews, /exercise-menu-trigger/)
assert.match(sessionViews, /exercise-context-menu/)
assert.match(sessionViews, /active-workout-title-row/)
assert.match(sessionViews, /active-workout-rename-btn/)
assert.match(sessionViews, /session-header/)
assert.match(sessionViews, /session-hub-link/)
assert.match(sessionViews, /session-title/)
assert.match(sessionViews, /session-stats-bar/)
assert.match(sessionViews, /stat-progress/)
assert.match(sessionViews, /rest-timer-dock/)
assert.match(sessionViews, /rest-timer-pill/)
assert.match(sessionViews, /rest-time-display/)
assert.match(sessionViews, /timer-pill-btn/)
assert.match(sessionViews, /current === undefined \|\| current <= 1 \? undefined : current - 1/)
assert.match(sessionViews, /current === undefined \|\| current <= 15 \? undefined : current - 15/)
assert.match(sessionViews, /active-finish-btn/)
assert.match(sessionViews, /Finish Workout/)

// The old per-set weight/reps editing table ("Adjust Weights & Reps") is gone entirely.
assert.doesNotMatch(sessionViews, /Adjust Weights & Reps|checklist-detail-toggle|<ActiveSetRow|<SetValueInput|set-count-pill/)
assert.doesNotMatch(sessionViews, /getPreviousPerformance|handleCopyPrevious|previous-copy-btn/)
assert.doesNotMatch(sessionViews, /is-active-set|activeSetIndex/)

// Mark Done is a single per-exercise action styled like the rest of the retro-square UI, using a check icon.
assert.match(sessionViews, /checklist-action-btn \$\{isComplete \? 'is-complete' : ''\}/)
assert.match(sessionViews, /<Check size=\{16\} strokeWidth=\{3\} aria-hidden="true" \/>/)
assert.match(sessionViews, /\{isComplete \? 'Done' : 'Mark Done'\}/)

// Finishing the workout calls completeActiveWorkout
assert.match(sessionViews, /async function handleFinishWorkout/)
assert.match(sessionViews, /await completeActiveWorkout\(workoutId\)/)

// The manual workout timer (start/pause/resume) is gone; only the between-set rest timer remains.
assert.doesNotMatch(sessionViews, /isWorkoutTimerPaused|pauseWorkout|resumeWorkout|getWorkoutDuration/)
assert.doesNotMatch(sessionViews, /START TIMER|ADD AN EXERCISE FIRST|timer-attempt-feedback|session-state-badge|stat-duration|pause-toggle-btn/)

assert.match(sessionViews, /exercise-header-title active-exercise-heading[\s\S]*className="exercise-name"[\s\S]*exercise-tag/)
assert.match(sessionViews, /exerciseCategorySnapshot, exerciseEquipment\.get\(item\.exercise\.exerciseId\)[\s\S]*join\(' · '\)/)
assert.match(repository, /deleteCompletedWorkout/)
assert.match(repository, /export async function startPreparedWorkout/)
assert.match(repository, /db\.transaction\('rw', db\.workouts, db\.workoutExercises, db\.workoutSets/)
assert.match(repository, /workout\.status !== 'completed'/)

assert.match(exerciseDex, /export interface ExerciseDexPicker/)
assert.match(exerciseDex, /onAddToRoutine\?: \(exercise: Exercise\) => void/)
assert.match(exerciseDex, /Add to routine/)
assert.match(exerciseDex, /exercise-picker-toggle/)
assert.match(exerciseDex, /exercise-picker-contextbar/)
assert.match(exerciseDex, />Added</)
assert.match(exerciseDex, /picker\.existingExerciseIds/)
assert.doesNotMatch(exerciseDex, /selectedExerciseIds/)

assert.match(css, /\.workout-hub \{[^}]*max-width: 480px[^}]*container: workout-hub \/ inline-size/s)
assert.match(css, /\.workout-hub-stack \{[^}]*display: grid;[^}]*min-width: 0/s)
assert.match(css, /\.workout-mission-card \{[^}]*border: 2px solid var\(--color-primary\)/s)
assert.match(css, /\.workout-mission-actions \{[^}]*minmax\(0, 1\.55fr\) minmax\(0, 1fr\)/s)
assert.match(css, /\.workout-week-grid \{[^}]*repeat\(auto-fit, minmax\(48px, 1fr\)\)/s)
assert.match(css, /@container\s*workout-hub\s*\(max-width:\s*350px\)[\s\S]*\.workout-mission-actions,\s*\.workout-replace-dialog\s*>\s*div\s*\{[^}]*grid-template-columns:\s*1fr;/s)
assert.match(css, /\.workout-hub-backdrop \{[^}]*safe-area-inset-bottom[^}]*overflow-y: auto/s)
assert.match(css, /\.workout-hub-rows strong \{[^}]*text-overflow: ellipsis[^}]*white-space: nowrap/s)
assert.match(css, /\.active-workout-final-actions \{[^}]*position: sticky;/s)
assert.match(css, /@media\s*\(max-width:\s*479px\)[\s\S]*\.routine-exercise-list\s*>\s*li\s*\{[^}]*grid-template-columns:\s*1fr;/s)
assert.match(css, /\.workout-finish-backdrop \{[^}]*position: fixed[\s\S]*\.workout-finish-backdrop\s*>\s*section \{[^}]*100dvh/s)
assert.match(css, /\.active-workout-final-actions \{[^}]*env\(safe-area-inset-bottom\)/s)
assert.match(css, /\.active-workout-page \{[^}]*max-width: 480px[^}]*container: active-workout \/ inline-size/s)
assert.match(css, /\.active-workout-page \{[^}]*gap: 0/s)
assert.match(css, /@container\s*active-workout\s*\(max-width:\s*350px\)[\s\S]*\.session-stats-bar\s*\{[^}]*flex-wrap:\s*wrap;/s)
assert.match(css, /\.app-main:has\(\.active-workout-page\) \{[^}]*padding: 0/s)
assert.match(css, /\.exercise-picker-contextbar \{[^}]*position: sticky;/s)
assert.match(css, /\.session-stats-bar \.rest-toggle-btn \{[^}]*min-height: 40px/s)
assert.doesNotMatch(css, /\.active-exercise-heading \{ min-height: 62px;/)
assert.match(css, /\.recent-workout-delete \{[^}]*min-height: 52px/s)

// The per-set editing table and the manual workout timer left no orphaned CSS behind.
assert.doesNotMatch(css, /\.active-set-row|\.set-row-actions|\.set-table-header|\.set-action-btn|\.set-inputs|\.proto-set-row|\.metric-label-long|\.metric-label-short/)
assert.doesNotMatch(css, /\.session-state-badge|\.stat-duration|\.pause-toggle-btn|\.active-workout-top-actions|\.workout-feedback\.timer-attempt-feedback/)

console.log('Workout UI assertions passed: Mission Stack states, guarded replacement, real data flows, responsive overlays, and theme tokens')
