/// <reference types="node" />
import assert from 'node:assert/strict'
import fs from 'node:fs'

const settings = fs.readFileSync('src/features/settings/SettingsPage.tsx', 'utf8')
const ui = fs.readFileSync('src/features/backup/BackupSettings.tsx', 'utf8')
const repository = fs.readFileSync('src/features/backup/backupRepository.ts', 'utf8')
const validation = fs.readFileSync('src/features/backup/backupValidation.ts', 'utf8')
const serializer = fs.readFileSync('src/features/backup/backupSerializer.ts', 'utf8')
const css = fs.readFileSync('src/styles/app.css', 'utf8')

assert.match(settings, /<BackupSettings \/>/)
assert.doesNotMatch(settings, /Backup tools arrive in a future phase|Automatic Backups|Backup Frequency|Backup Location|Number of Backups Retained|SoonButton/)
assert.match(ui, /Protect your FitDex data with a portable backup/)
assert.match(ui, /> Create Backup</)
assert.match(ui, /Choose \.fitdex File/)
assert.match(ui, /Your data stays on your device unless you choose to save or share the backup elsewhere/)
assert.match(ui, /Exercise videos and built-in app assets are not included/)
assert.match(ui, /readFitDexBackupFile\(file\)/)
assert.match(ui, /Validated backup/)
assert.match(ui, /This will replace the FitDex data currently stored on this device/)
assert.match(ui, /role="alertdialog"/)
assert.match(ui, /Back Up Current Data First/)
assert.match(ui, /openCreate\(true\)/)
assert.match(ui, /createBackup\(dialog\.returnToRestore\)/)
assert.match(ui, /Replace & Restore/)
assert.match(ui, /Restore Complete/)
assert.match(ui, /externalPreferenceFailures/)
assert.match(ui, /Your FitDex data was restored, but this browser could not persist/)
assert.match(ui, /window\.location\.reload\(\)/)
assert.match(ui, /role=\{isError \? 'alert' : 'status'\}/)
assert.match(ui, /aria-modal="true"/)
assert.match(ui, /headingRef\.current\?\.focus\(\)/)
assert.match(ui, /event\.key === 'Escape'/)
assert.match(ui, /event\.key !== 'Tab'/)
assert.match(ui, /querySelectorAll<HTMLElement>/)
assert.match(ui, /accept="\.fitdex,application\/x-fitdex-backup,application\/json"/)
assert.match(ui, /createFitDexBackup\(APP_VERSION\)/)
assert.match(serializer, /new Blob/)
assert.match(serializer, /URL\.createObjectURL/)
assert.match(serializer, /link\.download = fitDexBackupFilename/)
assert.match(serializer, /URL\.revokeObjectURL/)
assert.match(repository, /database\.transaction\('rw', tables/)
assert.match(repository, /where\('source'\)\.equals\('custom'\)\.delete\(\)/)
assert.match(repository, /restoreLocalPreferences\(backup, storage\)/)
assert.match(validation, /file\.size > FITDEX_BACKUP_MAX_BYTES/)
assert.match(css, /\.backup-dialog \{[^}]*100dvh[^}]*overflow-y: auto[^}]*overscroll-behavior: contain/s)
assert.match(css, /@media \(max-width: 374px\)[\s\S]*\.backup-preview > div, \.backup-complete-summary > div \{ grid-template-columns: 1fr;/)
assert.match(css, /@media \(min-width: 600px\)[\s\S]*\.backup-dialog-actions-three \{ grid-template-columns: repeat\(3,/)
assert.doesNotMatch(ui, /Cloud backup|automatic backup|synced/i)

console.log('Backup UI assertions passed: existing Settings integration, create/download, validated preview, double confirmation, safety backup, completion reload, responsive dialogs, and accessibility')
